- index.js
- package-lock.json
- package.json
This uses the new `hasFramework()` method from `@netlify/framework-info` to simplify the framework detection logic.
This PR also removes the framework detection inside `onPostBuild` since, if the project is not using Next.js, the build would have already failed due to the `failBuild()` in `onPreBuild`.
This PR does not fix line indentation in order to make the git diff clearer, but line indentation should probably be fixed after merge.
> Improve framework detection

- index.js
This adds the new `packageJson` argument passed to plugin handlers, which helps simplifying code and handle any edge case (for example, the current code did not work when using a `base` directory with a `package.json` several directories above it).
Note: you will need to upgrade Netlify Build to `5.1.0` (the version is shown in build logs) to try this locally. Until we make a release of the CLI, in the repository which uses `netlify-cli`, this can be done by removing your `package-lock.json` and `node_modules`, then running `npm install` again. If installed globally, this can be done by re-installing `netlify-cli` globally.
> Use `packageJson`

- .prettierignore
- .prettierrc.json
- helpers/isStaticExportProject.js
- index.js
- package-lock.json
- package.json
> add prettier & prettier-ignore & pre-commit hook

- .github/workflows/test.yml
- .gitignore
- .prettierignore
- __mocks__/cpx.js
- __mocks__/make-dir.js
- __mocks__/makef.js
- __mocks__/next-on-netlify.js
- index.js
- package-lock.json
- package.json
- sample/.gitignore
- sample/TESTING.md
- sample/netlify.toml
- sample/package-lock.json
- sample/package.json
- sample/pages/_app.js
- sample/pages/api/test.js
- sample/pages/index.js
- sample/pages/test.js
- sample/plugins/netlify-plugin-nextjs/index.js
- sample/plugins/netlify-plugin-nextjs/manifest.yml
- sample/styles/Home.module.css
- sample/styles/globals.css
- test/index.js
this also addresses https://github.com/netlify/netlify-plugin-nextjs/issues/8 and https://github.com/netlify/netlify-plugin-nextjs/issues/12
1. we see that exact error in issue #8 running tests if next isnt installed in the project. should i try to mock it? :/
2. seems we don't need hasFramework anymore with the next require try/catch. also when this is upgraded to a core plugin, won't the framework check be done outside of the plugin?
3. tried to mock `fs` in the standard way i mock the other dependencies and ran into a handful of issues. i now use the mock-fs package but calling mockFs broke the internals of `hasFramework` despite efforts to pass a correct config to mockFs that would appease hasFramework ☹️
> add some initial lightweight testing

- index.js
- test/index.js
Fixes #11.
The following line:
https://github.com/netlify/netlify-plugin-nextjs/blob/7b9a2430f46da57a38c5c85d611b2fc7df6bd777/index.js#L59
Is checking the `build.functions` configuration property in `netlify.toml`. However, [`constants.FUNCTIONS_SRC`](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#constants) should be used instead, since it takes more cases into account, such as when users are creating functions directory during build.
> Functions UI build settings

- index.js
- package.json
Fixes #30.
`fs.exists()` is [deprecated](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback).
We should use alternatives such as [`path-exists`](https://github.com/sindresorhus/path-exists) instead.
> Fix deprecated method

- index.js
Fixes #23.
The following check:
https://github.com/netlify/netlify-plugin-nextjs/blob/2849dc5f7c57e9fd827a939e067a871e4cb487b1/index.js#L26
Can be removed since `netlifyConfig` is always defined.
> Remove `netlifyConfig` check

- .github/workflows/test.yml
Fixes #21.
We should run CI tests on Windows and macOS as well, to ensure this plugin works for Netlify CLI users who run `netlify build`.
Many of our CLI users are on Windows (example for [`next-on-netlify`](https://github.com/netlify/next-on-netlify/issues/56#issuecomment-709670418)).
This PR also runs Node only in Node 10 and 14 (not 12) to make CI tests faster. In my experience, it is very rare for something not to work in a specific Node.js release but not in both the previous and the next major release.
> Run tests on Windows

- index.js
- test/index.js
Fixes #22.
The line checks for `packageJson` being falsy:
https://github.com/netlify/netlify-plugin-nextjs/blob/2849dc5f7c57e9fd827a939e067a871e4cb487b1/index.js#L21
However, when a site has no `package.json`, `packageJson` is an empty object. Therefore, `Object.keys(packageJson).length === 0` should be used instead.
This PR also adds a test for it.
> Fix `package.json` validation

- __mocks__/cpx.js
- __mocks__/make-dir.js
- __mocks__/makef.js
- __mocks__/next-on-netlify.js
- index.js
- package-lock.json
- package.json
- test/fixtures/invalid_next_config/next.config.js
- test/index.js
I am hitting two issues with `mock-fs`: [here](https://github.com/tschaub/mock-fs/issues/239) and [there](https://github.com/tschaub/mock-fs/issues/213).
When I try to add more tests, I get:
```
RUNS  test/index.js
node:fs:1732
handleErrorFromBinding(ctx);
^
Error: ENOENT: no such file or directory, lstat '/home/ether/netlify/netlify-plugin-nextjs/node_modules/jest/node_modules/chalk'
at Object.realpathSync (node:fs:1732:7)
at toRealPath (node:internal/modules/cjs/loader:368:13)
at tryFile (node:internal/modules/cjs/loader:364:10)
at tryExtensions (node:internal/modules/cjs/loader:376:22)
at tryPackage (node:internal/modules/cjs/loader:322:5)
at Function.Module._findPath (node:internal/modules/cjs/loader:540:18)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:887:27) …
```
> Use test fixtures

- index.js
- test/index.js
Under the hood, `utils.build.failBuild()` is throwing an error.
However, in tests, it is mocked with an empty function. This means the control flow continues because the code does not have any `return` statement after `failBuild()`. This means tests end up in odd situation where they are reaching lines of code that should never been hit in production.
This PR tries to fix this by:
- Adding `return` statements after `utils.build.failBuild()`
- Instead of mocking `utils.build.failBuild()`, replacing it with a simple function that throws an error. The tests then need to assert that an error is thrown from the `async onPreBuild` function, which is done in Jest with `await expect(onPreBuild(...)).rejects.toThrow('error message')`, as opposed to looking for mock calls.
> Fix `failBuild()` testing

- index.js
- package.json
- test/fixtures/deep_invalid_next_config/next.config.js
- test/index.js
Fixes #24
In a monorepo setup, it is possible that `next.config.js` might be in a parent directory if the user has set a `base` directory.
Next.js is searching `next.config.js` in parent directories using [`find-up`](https://github.com/sindresorhus/find-up):
https://github.com/vercel/next.js/blob/497cac4b93de9ecf6c7ed79bd6557dcd3bb51be5/packages/next/next-server/server/config.ts#L450
However we are not currently searching it in parent directories:
https://github.com/netlify/netlify-plugin-nextjs/blob/2849dc5f7c57e9fd827a939e067a871e4cb487b1/index.js#L57
Using `find-up` should fix this bug.
This also adds a test for it.
> Fix `next.config.js` resolution

- index.js
- package.json
- test/index.js
Fixes #27.
We just released in production the possibility for Build plugins to create a Functions directory even if the site does not have one. 
Thanks to this, we can now use `constants.FUNCTIONS_SRC` in order to use the site's Functions directory. 
It none was configured, the default Functions directory is used: this is named `netlify-automatic-functions` for the moment, but we will probably eventually rename it to `netlify-functions` (see [issue](https://github.com/netlify/build/issues/2016#issuecomment-726755971)).
> Use the site's Functions directory

- .github/workflows/test.yml
- package.json
Fixes #12.
This makes our Node.js support precise `>=10.13.0` since this is what Next.js 9 supports.
> Make Node.js support precise

- helpers/validateNextUsage.js
- index.js
- package-lock.json
- package.json
Fixes #26 and https://github.com/netlify/netlify-plugin-nextjs/issues/8
Also part of https://github.com/netlify/netlify-plugin-nextjs/issues/25
This makes `next` a peer dependency, which allows users to define which Next.js version they prefer (among the versions we support).
It a site is not using `next`, an error message is shown.
This also changes the version range of `next` from `^9.5.3` to `>=9.5.3` so that Next.js 10 users can use this, although support is experimental and we will print a warning message (to be done in separate PR).
Testing this turns out to be quite complicated. Making `require('next')` fail in automated tests is pretty hard to achieve without mocking `require()` which could bring its own sets of problems. Tests need `next` as a `devDependency` to run properly, so …
> Make `next` a peer dependency

- helpers/validateNextUsage.js
- package-lock.json
- package.json
Part of https://github.com/netlify/netlify-plugin-nextjs/issues/25
This adds some validation checks to ensure that users are not using an old version of Next.js.
This also prints a warning for users with Next.js 10.
> Validate Next.js version

- index.js
Discussion at https://github.com/netlify/netlify-plugin-nextjs/issues/10
The `npm install next-on-netlify` can be simplified to `npm install next-aws-lambda` instead (which should be slightly faster).
@lindsaylevine can you please confirm this still works?
> Improve `npm install` fix

- index.js
- package-lock.json
- package.json
- sample/.gitignore
- sample/netlify.toml
- sample/package-lock.json
- sample/package.json
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/43
wasn't quite sure how to replace the tests now that the manual copying is no longer a part of the plugin. making a note to add a specific test for this in next-on-netlify.
> pass constants FUNCTIONS_SRC and PUBLISH_DIR to nextOnNetlify

- index.js
⚠️ TO DO BEFORE MERGING ⚠️ 
- publish NoN
- install latest NoN in here
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/10
> remove next-aws-lambda install since NoN no longer depends on it

- index.js
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/47
> fail build if app is using NoN already

- README.md
- sample/pages/server-side.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/44
this will definitely be a work in progress over the next day. please comment/suggest whatever.
> update README ahead of UI one-click zero-config install

- .gitignore
- .prettierignore
- helpers/isStaticExportProject.js
- index.js
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/67
cc @racedale @bjonamu @olegrjumin @ahaasler @henningmu
> #67 next export unused script mistakenly failed builds

- README.md
- package-lock.json
- package.json
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/74
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/85
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/84
next-on-netlify 2.8.1 now has file tracking per https://github.com/netlify/next-on-netlify/pull/134. this is definitely a bandaid but a decent one to get people using the CLI who want to use it. i updated the README to recommend a workflow for managing the git file tracking until we can come up with a better solution.
> upgrade NoN to 2.8.2, explain CLI usage workflow in README, add jimp

- README.md
See https://netlify.slack.com/archives/C012GT6MYKU/p1611309758022200 and https://github.com/netlify/build/issues/2193
When creating a new site on Netlify, our UI looks in repo `netlify.toml` (if exists) and recommends a build command and publish directory based on its content.
Missing the `publish` setting causes our UI to recommend an empty directory (we'll follow up with another fix in our UI code).
> docs: add publish directory to netlify.toml

- .gitignore
- README.md
- index.js
- test/index.js
With https://github.com/netlify/build/pull/2188, the default functions directory will be `netlify/functions`. This PR updates the plugin accordingly.
> Use new default functions directory

- helpers/doesNotNeedPlugin.js
- helpers/doesSiteUseNextOnNetlify.js
- helpers/hasCorrectNextConfig.js
- helpers/isStaticExportProject.js
- helpers/validateNextUsage.js
- index.js
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/93
for the test cases that previously tested the failure points, i'm thinking i could just test that it _doesnt_ copy the expected files over in onBuild()? curious if yall have a better idea for testing that the plugin does nothing lol
> update failure points in plugin to do nothing instead

- package.json
This decrease the npm package size, from `53KB` to `6.7KB`.
Before:
```
npm pack --dry
npm notice 
npm notice 📦  @netlify/plugin-nextjs@2.0.0
npm notice === Tarball Contents === 
npm notice 2.0kB  CHANGELOG.md                                                               
npm notice 5.5kB  CODE_OF_CONDUCT.md                                                         
npm notice 1.1kB  LICENSE.md                                                                 
npm notice 6.6kB  README.md                                                                  
npm notice 606B   .github/ISSUE_TEMPLATE/bug_report.md                                       
npm notice 595B   .github/ISSUE_TEMPLATE/feature_request.md                                  
npm notice 822B   .github/workflows/fossa.yml …
```
> chore: decrease package size

- README.md
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/97
would love your feedback as well @amuttsch!
> update README with info about deploy contexts

- .gitignore
- helpers/doesNotNeedPlugin.js
- helpers/hasCorrectNextConfig.js
- index.js
- test/fixtures/broken_next_config/next.config.js
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/78
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/79
not 100% sure about trying to pass in the exact error from the catch into `failBuild`, open to thoughts!
> fail build if plugin cant load next.config.js

- .github/workflows/test.yml
`actions/setup-node@v2` is more reliable as it uses a cache of Node.js releases (doesn't fail when Node.js site is down).
> chore: update setup-node github action

- package.json
I don't see a reason to publish these files, but I might be wrong.
Before:
```
npm notice package size:  74.1 kB                                 
npm notice unpacked size: 315.6 kB 
```
After:
```
npm notice package size:  24.6 kB                                 
npm notice unpacked size: 87.0 kB 
```
> fix: don't publish test files

- helpers/getNextConfig.js
- helpers/hasCorrectNextConfig.js
Part of https://github.com/netlify/netlify-plugin-nextjs/issues/79
This separates `getNextConfig()` so it can be re-used (at the moment, this code is present in two different places).
In a follow-up PR, I will remove the duplicate code at https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/helpers/getNextConfig.js
> chore: separate `getNextConfig()`

- src/lib/pages/getStaticProps/setup.js
Fixes #116
`isRouteWithFallback()` was recently made async.
https://github.com/netlify/netlify-plugin-nextjs/blob/61b61f57d58ae095e3522c86013c75823911179b/src/lib/helpers/isRouteWithFallback.js#L3
However, one of its callers is missing the `await` keyword, which means it will always return `true`
https://github.com/netlify/netlify-plugin-nextjs/blob/61b61f57d58ae095e3522c86013c75823911179b/src/lib/pages/getStaticProps/setup.js#L41
> fix: fix missing `await` keyword

- helpers/validateNextUsage.js
- src/lib/helpers/getSortedRedirects.js
Partially addresses https://github.com/netlify/netlify-plugin-nextjs/issues/117
This ensures `next` is dynamically required.
Note: this does not address dynamically requiring `next` when `next.config.js` is loaded. A follow-up PR will fix this.
> fix: fix dynamic `require()` of `next`

- package-lock.json
- package.json
Fixes #126.
We use the `find-cache-dir` dependency but do not include it in our `package.json` `dependencies`.
https://github.com/netlify/netlify-plugin-nextjs/blob/61b61f57d58ae095e3522c86013c75823911179b/src/lib/steps/prepareFolders.js#L3
https://github.com/netlify/netlify-plugin-nextjs/blob/61b61f57d58ae095e3522c86013c75823911179b/src/lib/helpers/handleFileTracking.js#L3
This creates [the following bug](https://app.bugsnag.com/netlify/netlify-build/errors/6046b6b369f47b0018d4901a) in production:
```
Could not import plugin:
Cannot find module 'find-cache-dir'
Require stack:
- /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/steps/prepareFolders.js
- /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js
- …
```
> fix: fix `find-cache-dir` missing dependency

- helpers/getNextConfig.js
- package-lock.json
- package.json
This fixes memoization of `getNextConfig()`.
Note: the tests seem to be failing. Work in progress.
> fix: fix memoization

- helpers/validateNextUsage.js
Fixes #130.
`next <10.0.6` is not expected to work with the current version of this plugin. Please let me know if this is not the case.
> fix: fix minimum Next.js version

- helpers/doesNotNeedPlugin.js
- helpers/doesSiteUseNextOnNetlify.js
- helpers/hasCorrectNextConfig.js
- helpers/isStaticExportProject.js
- helpers/validateNextUsage.js
- index.js
- test/index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/144
I created 2 branches out of the `v1.1.1` tag:
1. `release_v1.1.1` to represent the release.
2. `fix/backport_no_op` to represent the fix.
This PR cherry picks https://github.com/netlify/netlify-plugin-nextjs/commit/b2718f299e27603d4def10e0ff2f3f831d8b8f6e and wants to merge it from `fix/backport_no_op` to `release_v1.1.1` so we can cut a release from that branch.
I also kept the experimental version as `10.0.0` (see https://github.com/netlify/netlify-plugin-nextjs/commit/723be5d3cf6d1bbef3b4cedcf438afda58035d21)
I tested this locally and it works (I used https://github.com/erezrokah/next-starter-jamstack which is the starter with the update to Next.js 10 reverted)
> fix: backport `update failure points in plugin to do nothing instead` to v1

- .gitignore
- README.md
- index.js
- package-lock.json
- package.json
- test/index.js
This PR backports more improvements available in the latest version of this plugin, but not available to Next 9 users to them being stuck on the `v1` on this plugin:
- Use `netlify/functions` instead of `netlify-automatic-functions` (https://github.com/netlify/netlify-plugin-nextjs/pull/87)
- Remove `next` as a peer dependency (https://github.com/netlify/netlify-plugin-nextjs/pull/96)
- Decrease npm package size (https://github.com/netlify/netlify-plugin-nextjs/pull/101)
_Important_: This PR should be merged to the `v1` git branch, not `main`. It should then be released as `1.*.*`, not `3.*.*`. `npm publish --tag=deprecated` should be used.
Also cc @erezrokah would did other backports on that branch.
> feat: backport more improvements for Next 9 users

- .github/workflows/release-please.yml
- CONTRIBUTING.md
- RELEASE.md
- commitlint.config.js
- package.json
This is what we use in our team for release automation.
It takes care of versioning, changelog generation, tagging and publishing GitHub releases.
On each commit to `main` `release-please` checks if there is something that justifies a release, based on conventional commit messages and then creates a relevant release PR (e.g https://github.com/netlify/cli/pull/1969).
Once the release PR is merged `release-please` tags the commit and creates a GitHub release.
To make this work, it requires writing commit messages in a specific way. See [here](https://github.com/googleapis/release-please#how-should-i-write-my-commits) for more information. 
There are other ways to automate releases, but we like this one as it doesn't require pushing directly to the default branch.
PR is at draft to get some …
> chore: add release please

- README.md
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/166
> chore: update README with note about version compatibility

- helpers/copyUnstableIncludedDirs.js
- index.js
- package-lock.json
- package.json
`unstableNetlifyFunctionsSupport` i think should be fine? `functions` was v unclear and this is just gonna be taken out anyways and prob only communicated to people who find the open issue so 🤷
> feat: unstableNetlifyFunctionsSupport.includeDirs configuration

- index.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/254
as discussed on slack, we can't/won't write a regression test for this (because we opted to not memoize in tests). instead, we will prioritize the refactor that removes memoization altogether.
> fix: nextConfig was memoized too early

- package-lock.json
- package.json
- src/lib/config.js
- src/lib/helpers/setupNetlifyFunctionForPage.js
- src/lib/pages/getStaticPropsWithFallback/setup.js
- src/lib/steps/setupRedirects.js
- src/lib/templates/functionBase.js
- src/lib/templates/imageFunction.js
- src/lib/templates/netlifyOnDemandBuilder.js
- src/tests/__snapshots__/defaults.test.js.snap
- src/tests/__snapshots__/i18n.test.js.snap
- src/tests/__snapshots__/optionalCatchAll.test.js.snap
- src/tests/preRenderedIndexPages.test.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/155
Addresses https://github.com/netlify/netlify-plugin-nextjs/issues/151
this was previously published as a tagged release to npm but now is safe for main!
> feat: use ODB (fallback pages + next/image)

- package-lock.json
- package.json
- src/lib/templates/imageFunction.js
This is a rewrite of the image function. The main fixes are improved error handling and new logic to determine output format. The logic for choosing the output format is as follows:
1. Determine the format of the input image by examining the buffer
2. If the format is SVG or GIF then we do not process it at all, so we redirect to the source image
3. If the format is unsupported (i.e. not JPEG, PNG, WebP or AVIF) then we fall-back to JPEG output
4. If the env var `FORCE_WEBP_OUTPUT` is set, then set output format to WebP. 
5. Otherwise, output format is the same as input format.
Fixes #307 and #312
> fix: refactor image function

- README.md
- index.js
- src/lib/templates/imageFunction.js
This PR adds an allowlist for remote images, to prevent the function being used to proxy arbitrary images. The standard way to support this is by setting a value in next.config.js, however we can't do this as we don't have access to this in the function. Instead we use an env variable and warn if the user sets the value in config instead.
This also adds docs for this and for the WebP env var
> fix: use allowlist for remote images

- README.md
> docs: update ToC

- package-lock.json
- package.json
- src/lib/helpers/copyDynamicImportChunks.js
- src/lib/helpers/runJobsQueue.js
- src/lib/pages/api/setup.js
- src/lib/pages/getInitialProps/setup.js
- src/lib/pages/getServerSideProps/setup.js
- src/lib/pages/getStaticProps/setup.js
- src/lib/pages/getStaticPropsWithFallback/setup.js
- src/lib/pages/getStaticPropsWithRevalidate/setup.js
- src/lib/pages/withoutProps/setup.js
- src/lib/pages/worker.js
- src/lib/steps/setupPages.js
This PR refactors the page setup so that each of the funcitons returns an array of jobs, rather than processing the pages at that time. This means we can run them in parallel, which we do with a queue. I don't have a large site to test this with, so it's hard to see what the effects are: the test sites are all under half a second already.
There is quite a bit of duplication still, with helpers that are almost identical, so there's scope for more refactoring.
Fixes #152
> perf: parallelize page setup

- src/lib/templates/imageFunction.js
The maximum Lambda response size is 6MB. This PR catches any response larger than this and returns an error instead.
Fixes #308
> fix: catch oversize image response

- src/lib/templates/imageFunction.js
Rotates the image automatically, using the exif rotation data (which we then strip from the image along with all metadata)
> fix: handle image rotation

- .github/workflows/test.yml
- src/lib/helpers/handleFileTracking.js
Follow up on https://github.com/netlify/netlify-plugin-nextjs/pull/328
> ci: set check_latest to true

- package-lock.json
- package.json
- src/lib/templates/imageFunction.js
Adds an etag header to images. We don't handle sending 304 responses because this is handled for us with an ODB
Fixes #372
> feat: add etag to image function

- src/lib/templates/functionBase.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/190
> chore: change func template to remove callback

- src/cypress/fixtures/next.config.js-with-basePath
- src/cypress/fixtures/pages/getServerSideProps/[id].js
- src/cypress/fixtures/pages/getServerSideProps/static.js
- src/cypress/integration/basePath_spec.js
- src/lib/config.js
- src/lib/helpers/convertToBasePathRedirects.js
- src/lib/helpers/formatRedirectTarget.js
- src/lib/pages/withoutProps/redirects.js
- src/lib/steps/setupRedirects.js
- src/tests/__snapshots__/basePath.test.js.snap
- src/tests/basePath.test.js
- src/tests/fixtures/next.config.js-with-basePath.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/131
note: my first stab at this work included touching every single pageType/redirects.js file (the way we did with i18n) to handle basePath there. with that flowing into several helpers and needing to import the config everywhere again, i opted for the performance cost of needing to loop over all the redirects after theyre collected (if there's a basePath configured) and building a new, basePath-supported collection of redirects. i have my old Logic Everywhere TM commit in a separate branch if anyone's curious lol
remaining issues:
> feat: support for basePath

- src/lib/helpers/convertToBasePathRedirects.js
- src/lib/helpers/formatRedirectTarget.js
- src/lib/pages/withoutProps/redirects.js
- src/lib/steps/setupRedirects.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/382
i had previously thought basePath defaulted to '' from loadConfig no matter what. thanks to some users who reported very quickly, that is not the case! these updated checks should fix the issue
> fix: basePath is undefined when a site has no config file

- README.md
This PR adds links from the README directly to the docs pages, rather than a single link to the dirctory which is not easy to use
> docs: add links from readme to docs pages

- src/lib/steps/copyNextAssets.js
I wound up spending an inordinate amount of time trying to debug issues when attempting to deploy with NX while using this plugin.
Having these specific details would have saved me a lot of trouble. Hopefully, this change will help others down the line.
Thanks for all of your work!
> fix: add details to copyNextAssets error messaging

- helpers/checkNxConfig.js
- helpers/getNextRoot.js
- index.js
- src/lib/steps/copyNextAssets.js
Fixes a bug where if the publish dir was set to an empty string, then the plugin would think that the root of the Next site was a sibling of that, i.e. it was the directory above the repo root. This PR changes a few things. First, it adds specific handling for empty `PUBLISH_DIR` and `netlifyConfig.build.publish` values when running locally, as well as handling for when the publish dir is the site root. Ideally we'd fail if somebody sets the site root as the publish dir, like we do in the Gatsby plugin, but that would be a breaking change, so instead we work around it.
This fixes the issue that broke some sites after 3.5.0 was released.
> fix: handle empty publish directory

- helpers/validateNextUsage.js
Increase the minimum version shown as experimental to 11.1.0, as 11.0 patch versions should be fine, and log the current Next.js version
Fixes #380
> chore: update min Next.js version, and log current

- helpers/doesNotNeedPlugin.js
- index.js
- test/index.js
If the build command is empty then we won't be able to generate anything, so skip running the plugin
> fix: skip plugin if build command is empty

- helpers/doesNotNeedPlugin.js
- helpers/isStaticExportProject.js
- helpers/usesBuildCommand.js
- index.js
- test/index.js
Currently if we detect a site as using Next.js and auto-install the plugin then builds will fail with an error message that isn't very intuitive. In a lot of cases these are actual Next.js sites, but the deployed site is building the STorybook rather than the actual site. This is a common enough pattern for it to be worth detecting specifically. This PR detects the `build-storybook` command and skips the plugin. It also adds an explicit check for the Next build directory after the build, and if it's missing it fails the build with links to docs on configuration or removing the plugin.
Fixes #495
> fix: handle Storybook and other sites that don't build

- docs/image-handling.md
- index.js
- src/index.js
- src/lib/steps/setupImageFunction.js
- src/lib/templates/imageFunction.js
- src/tests/defaults.test.js
- src/tests/fixtures/next.config.js
Currently we require users to set an env var to specify allowed domains for images. This is because the next config is not available inside the function at runtime. This is not ideal from a DX perspective, but is particularly bad because of the fact that funcitons can only use env vars that have been set in the UI, not in the toml.
This PR instead writes a snapshot of the image config as a JSON file in the image function dir, while can then `require()` it. It still supports the env var for compatibility reasons, by merging any domains specified there. However it also emits a warning telling the user to switch to using the `next.config.js` instead.
Fixes #516
> feat: add support for using image config from next.config.js

- package-lock.json
- package.json
- src/lib/config.js
- src/lib/pages/getStaticProps/redirects.js
- src/lib/pages/getStaticProps/setup.js
- src/lib/pages/getStaticPropsWithFallback/redirects.js
- src/lib/pages/getStaticPropsWithFallback/setup.js
- src/lib/pages/getStaticPropsWithRevalidate/redirects.js
- src/lib/pages/getStaticPropsWithRevalidate/setup.js
- src/tests/defaults.test.js
- src/tests/i18n-ssg-root-index.test.js
- src/tests/i18n.test.js
Currently we are using paths generated by path.join to generate paths for require(), which causes issues on Windows. This PR wraps the calls in slash(), which switches everything to use / posix-style paths, which is what require() expects.
> fix: use POSIX paths for Windows require()s

- src/lib/templates/imageFunction.js
Disables png and jpeg optimisation temporarily because it's very slow. This means the output images are larger, but it was unacceptably slow to process. We'll address this with the new image function. We also disable the redirect when requesting images larger than the source. Instead we just disable upsizing. Redirecting meant we'd need to request the source image twice, which was expensive.
Fixes #507
> fix: disable png palette

- helpers/usesBuildCommand.js
- test/fixtures/not-static.json
- test/fixtures/static.json
The update to catch more static export scenarios caused a regression that caused some others to be missed. This PR moves the build command into a fake extra npm script, meaning the `parsePackageJson` module can handle the parsing, and catch more cases. 
Fixes #528
> fix: catch more export cases

- .eslintrc.js
- helpers/cacheBuild.js
- index.js
- test/index.js
When caching a build, the distDir wasn't being found in monorepos, because it wasn't accounting for `nextRoot`. This PR ensures that nextRoot is used.
Fixes #500
> fix: handle monorepo caching

- README.md
- helpers/doesNotNeedPlugin.js
- helpers/usesBuildCommand.js
- test/index.js
This PR adds support for an env var `NEXT_PLUGIN_FORCE_RUN`, which skips autodetection and forces the plugin to either always run (if set to `"true"` or `"1"`) or never run (if set to `"false"` or `"0"`)
Fixes #546
> feat: add NEXT_PLUGIN_FORCE_RUN to skip auto-detection

- src/lib/helpers/setupNetlifyFunctionForPage.js
- src/lib/templates/getTemplate.js
- src/tests/configurableDirs.test.js
- src/tests/defaults.test.js
- src/tests/i18n.test.js
- test/index.js
This PR switches the function entrypoints back to js from ts, so it no lonegr forces esbuild. Users can still specify esbuild and get the performance gains, but we won't force them until we're able to do staged rollouts of plugin versions.
> chore: don't use esbuild by default

- src/lib/pages/getStaticPropsWithRevalidate/pages.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/469
> chore: log warning about isr

- index.js
The default behavior in versions of Node < 15 is to just warn when a promise rejection is unhandled. This means that often we can't tell if the build has failed until we try to copy the built artifacts. This PR adds `--unhandled-rejections=strict` to `NODE_OPTIONS`, meaning that unhandled rejections fail the build early. This should not be a breaking change, because these builds already fail but it's just later and incorrectly appears to be a plugin error rather than a build error.
> fix: exit on unhandled promise rejection in build

- src/lib/config.js
- src/lib/helpers/convertToBasePathRedirects.js
- src/lib/helpers/getPreviewModeFunctionName.js
- src/lib/helpers/isRouteWithFallback.js
- src/lib/helpers/setupNetlifyFunctionForPage.js
- src/lib/pages/getStaticProps/pages.js
- src/lib/pages/getStaticProps/redirects.js
- src/lib/pages/getStaticPropsWithFallback/redirects.js
- src/lib/pages/getStaticPropsWithFallback/setup.js
- src/lib/templates/getTemplate.js
- src/tests/__snapshots__/basePath.test.js.snap
- src/tests/__snapshots__/defaults.test.js.snap
- src/tests/__snapshots__/i18n.test.js.snap
- src/tests/defaults.test.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/440
> fix: preview mode for odb/fallback pages

- .gitignore
- demo/next.config.js
- helpers/verifyBuildTarget.js
- index.js
By default Next.js generates random build IDs. This means that every build will generate changed files, which means they need to be deployed every time. This PR changes the generated `next.config.js` to use a static build ID, and adds an `onPostBuild` check that logs a warning if it's using random IDs.
Fixes  #604
> feat: try to generate stable build ids

- .github/workflows/test.yml
Because Next.js has dropped support for Node 10, we can drop it from tests too. Instead, I've added tests on Node 12, which is the current minimum version
> chore: update node version in tests

- package-lock.json
- package.json
- src/helpers/files.js
- test/index.js
Switch to globby rather than tiny-glob. The pattern fails as-is, but it supports separate negated globs which then work
Note that tests pass on Windows
Fixes #776
> fix: switch to globby for static files

- README.md
All of the `Docs` links are pointing to the wrong branch.
**Before:**
**After:**
1. Visit the Deploy Preview ([insert link to specific page]())
...
---
> fix: links to docs are pointing to wrong branch

- README.md
- docs/middleware.md
Adds some docs on using Next 12 middleware on Netlify. 
[Rendered version](https://github.com/netlify/netlify-plugin-nextjs/blob/mk/middleware-docs/docs/middleware.md)
Fixes #775
> feat: add docs on middleware

- src/templates/getHandler.js
Ensure paths are URL-encoded. Uses the `URL` constructor, because it avoids double-encoding if the path is already encoded.
1. Visit the Deploy Preview, with a path that included a space or special character. Site should give a custom 404, rather than a 502 error
- [Main branch](https://netlify-plugin-nextjs-demo.netlify.app/hello%20world) 
- [This PR](https://deploy-preview-800--netlify-plugin-nextjs-demo.netlify.app/hello%20world)
Closes #786
---
> fix: ensure path is encoded

- docs/middleware.md
Some small updates to the new middleware docs, to reflect the fact that the fix has been released in next@canary
The PR also includes formatting changes: only the "Caveats" section has content changes
> chore: update middleware docs wording

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/pull_request_template.md
- .prettierignore
Updates the PR and issue templates
> chore: update issue and pr templates

- package-lock.json
- package.json
- src/helpers/verification.js
- src/index.js
- test/index.js
The old version of the plugin generated lots of functions which may be still lying around in users' sites, either checked-in to scm or just uncleaned in a build directory. These can cause errors and slow builds. This PR detects any functions called `next_*` (which was the naming convention) and warns the user that they should delete them.
Create a function in the demo project, either in `.netlify/internal-functions` or `netlify/functions`, with a name starting with `next_`. Run a build and note the warning.
Fixes #772
> feat: log warning if old functions exist

- docs/large-functions.md
- docs/middleware.md
- src/index.js
- test/index.js
This PR changes the `EXPERIMENTAL_MOVE_STATIC_FILES` mode to be the default, so any statically-rendered pages are served from the CDN rather than the origin, unless they match middleware. It adds a new env var `SERVE_STATIC_FILES_FROM_ORIGIN` to disable the mode.
> feat: move static pages by default

- src/helpers/functions.js
- src/templates/getHandler.js
- src/templates/handlerUtils.ts
- test/index.js
Removes the runtime requirement for node-fetch with a helper that uses Node builtins
1. See unit tests
> feat: replace node-fetch with builtin

- demo/next.config.js
- demo/pages/old/image.js
- demo/pages/redirectme.js
- src/helpers/files.js
- test/index.js
Ensures that if a file would match a redirect or `beforeFiles` rewrite, it isn;t served from the CDN as that would prevent the rule from being applied. We could potentially be smarter and check if we can represent the rule using Netlify redirects, but that would be quite complicated to achieve and wouldn't work for lots of scenarios
1. Visit these pages and ensure they redirect to the locale root: [en](https://deploy-preview-832--netlify-plugin-nextjs-demo.netlify.app/redirectme) [fr](https://deploy-preview-832--netlify-plugin-nextjs-demo.netlify.app/fr/redirectme)
2. Visit these pages and ensure that they show the image page, rather than an error message: [en](https://deploy-preview-832--netlify-plugin-nextjs-demo.netlify.app/old/image/) …
> fix: don't move files to the CDN if they match redirect/rewrite rules

- src/helpers/config.js
Handle situation where the i18n object is missing in the normalised config
> fix: handle missing i18n object

- demos/default/.env.production
- demos/default/pages/api/hello.js
- demos/default/pages/getServerSideProps/[id].js
- demos/default/pages/getStaticProps/env.js
- package.json
- src/helpers/config.js
- test/__snapshots__/index.js.snap
- test/index.js
Adds support for [Next env var files](https://nextjs.org/docs/basic-features/environment-variables)
Check the following pages for the string "Hello Production"
1.  https://deploy-preview-842--netlify-plugin-nextjs-demo.netlify.app/getStaticProps/env
2. https://deploy-preview-842--netlify-plugin-nextjs-demo.netlify.app/api/hello
3. https://deploy-preview-842--netlify-plugin-nextjs-demo.netlify.app/getServerSideProps/1
Fixes  #823
> feat: add support for Next env vars

- src/helpers/redirects.ts
The root level redirect when NEXT_LOCALE is set was incorrectly defined when trailingSlash was set to false.
1. Set a test site to trailingSlash = false
2. Check that there is no redirect created with `from = ''` 
Fixes #872 
---
> fix: correct root redirect when trailingSlash = false

- src/helpers/redirects.ts
- src/index.js
Currently we have a forced redirect to the handler funciton if preview mode is on, as it needs to bypass ODBs and SSG pages. However this means it also forces a rewrite for files from `public`, causing broken images and other static files. This PR adds no-op rewrites for any files from that directory, ensuring that they don't match the force redirect and are instead served from the CDN.
2. [Enable preview mode on the deploy preview](https://deploy-preview-918--netlify-plugin-nextjs-demo.netlify.app/api/enterPreview/)
3. [Load the image from the index page](https://deploy-preview-918--netlify-plugin-nextjs-demo.netlify.app/next-on-netlify.png) and check it is found
Closes #753 
---
> fix: bypass preview for static files

- demos/default/netlify.toml
- src/templates/getHandler.ts
Netlify Functions events have a bug where the `event.path` is decoded, so can end up with illegal characters. To work around this, this PR switches to using `rawUrl` directly, which is still encoded. This bug was manifesting when a URL contained an encoded `#` character, which if decoded would cause the rest of the URL to be treated as a fragment rather than part of the path.
1. Visit the Deploy Preview ([on this page](https://deploy-preview-954--netlify-plugin-nextjs-demo.netlify.app/shows/73/whatever/path/zIFeVeR%232711/you/want/)) 
2. Verify the path displayed in the page includes the `#` character (%23)
Fixes #952
---
> fix: use `rawUrl` for path

- demos/default/netlify.toml
- src/helpers/cache.ts
- src/helpers/functions.ts
- src/index.ts
- src/templates/getPageResolver.ts
- test/__snapshots__/index.js.snap
- test/index.js
Changes the way paths are generated for `getPageResolver`, because the current way is causing trouble on Windows. Updated the tests so that they're more able to catch this.
1. Ensure the tests pass on WIndows
Fixes #941
---
> fix: handle Windows paths correctly

- cypress/integration/static-root/i18n.spec.ts
Currently every build fails on the Cyporess Accept-Encoding test, but that's because of a libredirect bug not anything in the plugin. This PR changes that test so that ti does pass now, though we should change it back once the redirects work properly so that it's more realsitic.
Check the static site cypress tests pass
> chore: fix accept-encoding test

- demos/default/netlify.toml
- demos/nx-next-monorepo-demo/netlify.toml
- demos/static-root/netlify.toml
Reverts the `ignore` commands in the test site, which were changed when diagnosing the missing builds problem
> chore: revert ignore command

- src/helpers/verification.ts
- test/index.js
If the plugin can't find a build in the `publish` directory it fails the build with a warning to check that the build command has run and the publish dir is correct. This PR adds specific wording if the publish dir is "out", because that is the old default.
Change the `publish` dir in `netlify.toml` to `"out"`, then run a build, checking that it fails with a message including `Your publish directory is set to "out", but in most cases it should be ".next".`
Fixes #975
---
> fix: warn if publish is "out"

- docs/isr.md
Adds docs for ISR. The README PR (#937) adds a section with a link to this doc.
[Rendered version](https://github.com/netlify/netlify-plugin-nextjs/blob/mk/isr-docs/docs/isr.md)
Fixes #151!!!
> chore: document ISR

- src/helpers/redirects.ts
- src/helpers/verification.ts
- src/index.ts
- test/index.js
If users have Netlify rewrites they could override the ones in the plugin, so this PR warns about them
Add a `_redirects` or toml file to the demo site that has a potentially problematic rewrite, such as `/badpath /404 404`, run a build and look for an error message
---
> chore: warn for problematic user rewrites

- src/helpers/files.ts
We avoid moving ISR pages to the CDN, by checking the files against the list of routes. This PR fixes a bug where if `/` was ISR and there were no locales defined, `index.html` would be moved to the CDN. This would cause an infinite loop where it tried to load itself.
I didn't think it worth creating a new test site for this, but it can be tested by making `static-root` use ISR for `index.js`, and disabling i18n.
---
> fix: prevent infinite loop when `/` is ISR

- src/index.ts
An env var flag was left in the release version which was handling the Next server patching.
- Load [deploy preview](https://deploy-preview-1051--netlify-plugin-nextjs-demo.netlify.app/getStaticProps/withRevalidate/2/)
- Check displayed build time
- Wait 1 minute, load again. Time may be the same. It it has updated, then it was already refreshed. If not move to next step.
- Wait another minute, then load again. Time should have updated.
It's time for the capybaras' annual yuzu onsen
Fixes #1028. Fixes #1035 
---
> fix: fix bug that caused ISR pages to sometimes serve first built version

- cypress/integration/default/default.spec.ts
- demos/default/pages/index.js
- src/templates/getHandler.ts
If `NODE_ENV` is unset, React uses a development build, which is slower and [can cause errors](https://github.com/netlify/netlify-plugin-nextjs/issues/1047). By default `NODE_ENV` is not set in Lambdas, so this happens for SSR pages. This PR forces the env to `"production"` if unset
1. Visit deploy preview
2. Check for "NODE_ENV: production"
Fixes #1047
---
> fix: force React to use production env

- src/helpers/redirects.ts
- src/helpers/types.ts
- test/index.js
Pre-Next 12, static routes weren't included in the routes manifest. We deal with that here with an optional chain.
1. Check the unit test
---
> fix: handle `routes-manifest`s without `staticRoutes` defined

- README.md
- src/templates/getHandler.ts
Adds request logging to both function handlers, as well as an update to the readme explaining what's up.
1. Visit the Deploy Preview
2. Load a page
3. View the function logs
Closes #1116 
---
> feat: add request logging

- demos/default/local-plugin/package-lock.json
- demos/default/pages/getStaticProps/withFallbackAndMiddleware/[...slug].js
- demos/default/pages/getStaticProps/withFallbackAndMiddleware/[id].js
- demos/default/pages/getStaticProps/withFallbackAndMiddleware/_middleware.js
- demos/default/pages/index.js
- src/helpers/files.ts
- src/helpers/redirects.ts
- src/helpers/utils.ts
- test/__snapshots__/index.js.snap
Routes that match middleware need to be served via SSR, because the middleware is run at the origin. This PR ensures that any routes that matches mdidleware is not served by an ODB, which was causing errors where results were persisted including the middleware.
1. Visit [the Deploy Preview](https://deploy-preview-1171--netlify-plugin-nextjs-demo.netlify.app/getStaticProps/withFallbackAndMiddleware/4/)
2. Check the network tab: there should be a header `x-middleware-date` inserted by middleware. Ensure that the date is up to date. Also ensure that `x-nf-render-mode` is `ssr`.
Fixes #1168, Fixes #1114
---
> fix: don't use ODB for routes that match middleware

- demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
- src/helpers/files.ts
- src/helpers/utils.ts
- test/__snapshots__/index.js.snap
- test/index.js
We need to patch the Next server source file because Next doesn't allow non-Vercel hosts to disable flushing of ISR pages to disk. In a recent update, the code in question was moved from `next-server` to `base-server`, meaning that the patch was not applied. This meant that ISR pages were serving the original built files rather than the updated version. This caused #1189 and possibly #1162.
This PR makes the patching process more robust, and introduces tests to ensure the patching is working in future
1. Visit [the Deploy Preview](https://deploy-preview-1190--netlify-plugin-nextjs-demo.netlify.app/getStaticProps/withRevalidate/withFallbackBlocking/2/)
2. Wait for a minute
3. Visit deploy preview again and ensure that the time has updated to near the current time, and not reverted to the …
> fix: correctly disable ISR disk flushing

- .github/workflows/test.yml
Currently we test `next@latest` and `next@canary` consecutively in the same test. This PR splits them out so that they can run faster and so canary tests can be optional.
1. Observe the tests both run. Canary will fail on a TypeScript error
---
> ci: split canary tests from latest

- .github/workflows/cypress-demo-nx.yml
- .github/workflows/cypress-demo-static.yml
- .github/workflows/cypress-demo.yml
Update machines according to Cypress dashboard guidelines. Also adds group naming for better understanding of test runs
See that tests in actions run as expected
https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action
---
> chore: Add details to cypress and remove extra matrix

- demos/nx-next-monorepo-demo/apps/demo-monorepo/pages/api/index.js
- src/templates/getHandler.ts
The handler currently changes the working directory to the site root, however if the site uses Nx the site root is moved within a 'dist' folder and SSR routes consequently fail.
1. Visit the Deploy Preview and check the /api route returns 'Hello World' json output
Fixes #1278 
---
> fix: correctly find site root when using SSR with Nx

- demos/nx-next-monorepo-demo/package-lock.json
- demos/nx-next-monorepo-demo/package.json
- package-lock.json
- package.json
- src/helpers/functions.ts
Updates the import path of a Typescript type.
1. Running `npm run build` now completes successfully. Previously this would fail.
Related pull request in NextJS that made the change: https://github.com/vercel/next.js/pull/34677
---
> chore: update the path for the import of type ImageConfigComplete

- cypress/integration/default/preview.spec.ts
- src/helpers/config.ts
- test/index.js
Resolves issues where AMP would work locally, but not on a deployed site.
Someone had reported an issue where they were able to see that pages configured for AMP were working in their local environments, but not when they were deployed to Netlify.
In testing, it appeared that the `terser` package was needed but was being omitted from the netlify function `.zip` file generated at the `onBuild` step.
Removing the line that omitted the terser bundle resolves the issue.
1. Visit the Deploy Preview
The test deploy site has the home page configured as a hybrid AMP page. This means that you can test both the non-AMP and AMP views.
AMP URL: https://624b075121937b095892dd5c--amp-nextjs-investigation-with-ci.netlify.app?amp=1
Non-AMP URL: https://624b075121937b095892dd5c--amp-nextjs-investigation-wi …
> fix: :bug: include terser bundle into netlify functions

- .github/workflows/test.yml
Runs the tests on a nightly basis. Also only run the canary tests on the `main` branch rather than on every push to a development/feature branch.
This affects Github Actions testing schedule configuration so no deploy site testing is needed
> ci: :sparkles: run tests on a nightly basis

- demos/middleware/netlify.toml
- demos/server-components/netlify.toml
- package-lock.json
- plugin/package.json
- plugin/src/helpers/edge.ts
Ensure that edge functions use the source TypeScript, rather than compiled js. Fixes the toml to ensure the env is properly set
1. Ensure the middleware demo builds correctly
---
> fix: copy edge src file 

- demos/middleware/pages/index.js
- demos/middleware/pages/shows/rewriteme/index.js
- plugin/src/templates/edge/utils.ts
Currently our middleware edge function wrapper strips any internal Next headers before returning them to the client. This is a mistake, because Next uses these headers during navigation. This PR adds them back in.
1. Visit the middleware deploy preview, https://deploy-preview-1322--next-plugin-edge-middleware.netlify.app/
2. Click the _Rewrite me_ link on the homepage
3. Ensure it's rewritten to a show the page at https://deploy-preview-1322--next-plugin-edge-middleware.netlify.app/shows/100
Fixes #1321 
---
> fix: pass x-middleware-rewrite header to client

- demos/middleware/pages/index.js
- demos/middleware/pages/shows/rewrite-absolute/_middleware.ts
- demos/middleware/pages/shows/rewrite-absolute/index.js
- demos/middleware/pages/shows/rewrite-external/_middleware.ts
- demos/middleware/pages/shows/rewrite-external/index.js
- plugin/src/templates/edge/utils.ts
When rewriting a URL in middleware, it attaches an `x-middleware-rewrite` header with the target URL. This is used both for server-side rewrites, but also for client-side preflights. The returned value can be either a relative or absolute URL. Previously we passed-through the header unchanged. This caused problems for two reasons. First, if it is an absolute URL it is treated as external by the router on the client, even if it is not, which caused Next to get into an infinite reload loop as it tried to redirect to itself. For actual external URLs it was failing because Netlify Edge Functions don't support rewriting to external URLs.
This fixes these problems in two parts:
- If the absolute URL is actually local then it makes it into a relative URL using [the same algorithm as …
> fix: handle absolute rewrite URLs

- demos/next-auth/package.json
In the demo site for `next-auth`, the `next-auth` dependency was listed as 'latest'. When using the 'latest' tag, v3 of next-auth was being installed rather than v4.
This was causing build errors because the type definitions used in the example project aren't introduced until v4.
---
> fix: specify version of next-auth

- demos/default/netlify.toml
This change forces rebuilds if there are any changes in the repo - fixing an issue where cypress tests fail on PRs if changes had been made outside of the default demo, or the plugin directory, as Netlify builds would be cancelled.
---
> chore: rebuild default demo if any changes are made in repo

- plugin/src/index.ts
- test/index.js
This was missed in the initial implementation of adding out of the box NextAuth support (see #1242 ), but is something that is needed when the `basePath` property exists within the `next.config.js` file. Related docs on NextAuth can be found [here](https://next-auth.js.org/configuration/options#nextauth_url)
1. Visit the Deploy Preview [here](https://deploy-preview-1336--netlify-plugin-nextjs-next-auth-demo.netlify.app/)
---
> feat: Include basePath property in NEXTAUTH_URL when present in config

- package-lock.json
- package.json
- plugin/src/index.ts
- test/index.js
As outlined in the issue linked below, a user could have defined `NEXTAUTH_URL` in the `next.config.js` file and ,prior to these changes, the plugin would override the value to set it to what `process.env.URL` is.
These changes check to see if a `NEXTAUTH_URL` already exists within the generated server files after building the site and will continue on if it exists, or generate a default value if one doesn't. 
Logging was added for the scenario where a user defined `NEXTAUTH_URL` exists in order to make it clear about what the plugin is seeing with respect to the `next-auth` related configuration.
These changes also add the `chance` package for unit tests so we can avoid hard coding test values where possible.
Fixes #1345 …
> fix: don't override user defined NEXTAUTH_URL

- demos/base-path/netlify.toml
- demos/default/netlify.toml
- demos/middleware/netlify.toml
- demos/next-auth/netlify.toml
- demos/next-export/netlify.toml
- demos/next-i18next/netlify.toml
- demos/nx-next-monorepo-demo/netlify.toml
- demos/server-components/netlify.toml
- demos/static-root/netlify.toml
Updates the demos' `ignore` commands so that the sites will all build if the plugin changes. It is different from before because it also will now build if the two commit hashes are the same. This is the case when the cache is cleared. Previously this would return a value of unchanged, meaning it wasn't possibel to manually build the demo sites.
1. Check that the sites build
---
> ci: build demos whenever plugin changes or cache cleared

- demos/middleware/middleware.ts
- demos/middleware/package.json
- demos/middleware/pages/index.js
- demos/middleware/pages/shows/static/[id].js
- package-lock.json
- plugin/src/templates/edge/runtime.ts
Next.js now runs middleware on internal data requests, so this PR updates the edge function to not skip these.
1. Load [the middleware demo](https://deploy-preview-1382--next-plugin-edge-middleware.netlify.app/)
2. Open network panel
3. Mouse over the "add header to static page" link
4. Check if the `3.json` request has an `x-middleware-date` header
When we have e2e canary tests, or it is released in Next then we can add tests for this.
---
> fix: run edge middleware on data requests

- .github/CODEOWNERS
- .github/pull_request_template.md
Adds @netlify/frameworks as codeowner, and changes the pull request template to mention frameworks instead of integrations
> chore: add codeowners and fixing pull request template

- package-lock.json
- plugin/src/index.ts
Fixes error if next does not add an `images` object to `experimental`.
---
> fix: check for existence of experimental images

- package-lock.json
- package.json
- plugin/package.json
This reverts commit 1770e7c65f156f8b5aedf2bf43b5f3898b4b7092 as it was causing issues with builds. Looking at the changes between `@netlify/build` 27.1.2 and 27.1.3, I'm still not sure why this is breaking things as the only change was validating the edge functions config, https://github.com/netlify/build/pull/4291. See https://github.com/netlify/build/releases/tag/build-v27.1.3
1. All the deploy previews should build now.
---
> chore: Revert "chore(deps): update dependency @netlify/build to ^27.1.3 (#1354)"

- plugin/src/helpers/edge.ts
Fix to problem building sites in versions of Next which don't define `functions` in middleware manifest
---
> fix: handle missing manifest functions field

- package-lock.json
- plugin/src/index.ts
Adds a check for sortedMiddleware to fix error here: https://app.bugsnag.com/netlify/netlify-build/errors/62bc82c51f3d1700080caab6?event_id=62bc82c50095183a54e70000&i=sk&m=nw
---
> fix: check for Middleware manifest & chain

- README.md
- demos/canary/next.config.js
- docs/isr.md
- plugin/src/helpers/edge.ts
- plugin/src/helpers/functions.ts
- plugin/src/index.ts
- plugin/src/templates/edge/ipx.ts
This PR enables content negotiation for images using edge functions to be opt-out, rather than opt-in. The PR ensures that the old redirect is also written, but it will not match if the edge function runs.
This PR also ensures that the edge function respects the Next image formats config option, which means that by default webp is the only modern format offered, but that AVIF is an option.
The PR adds some docs on the behaviour, as well as some general information about image handling. I rearranged some of the docs to adjust priorities.
@KyleBlankRollins This adds a new env var: `NEXT_DISABLE_EDGE_IMAGES`, which disables the edge fucntion used for content negotiation and instead always serves the fallback format (jpg or png)
1. Load the default demo deploy preview and check that the image …
> feat: use edge functions for content negotiation by default

- plugin/src/templates/edge/ipx.ts
Explicitly type the imageconfig.json in the ipx content negotiation edge function. This fixes a bundling error in the case where the Next config is missing the formats key, meaning the inferred type was invalid.
> fix: explicitly type image config in ipx edge function

- plugin/src/templates/edge/runtime.ts
Gets the client IP address from the Context object rather than the header.
> feat: get client IP from Context object rather than header

- plugin/src/helpers/edge.ts
- plugin/src/templates/edge/ipx.ts
- test/index.js
Currently the ipx edge function imports the `imageconfig.json` from `functions-internal/_ipx`. However this was causing problems when using ESZIP for bundling. This PR changes it to copy the JSON file into the  edge functions dir and imports it as a sibling file. This works as expected.
In the `demos/default` directory, run `node ../../node_modules/@netlify/build/src/core/bin.js --featureFlags=edge_functions_produce_eszip`
---
> fix: copy imageconfig into edge function dir

- package.json
- plugin/src/helpers/verification.ts
- test/helpers/verification.spec.ts
Adds better error messaging for when:
* a user has a built site that's not detected
* the user has set the publish directory to something other than `.next`
* the netlify plugin detects a production build in the `.next` folder
* Go to demos/default test project and build it such that there's a production build in the `.next`
* Change the `publish` directory in `demos/default/netlify.toml` to something other than `.next`
* Attempt to build the project using `ntl build`
**Expected behaviour:** You should see an updated error message prompting you to set the 'publish' directory to `.next` due to detecting the presence of a production build in that directory
Fixed #1362
> fix: add better error messaging for builds

- .vscode/launch.json
- demos/default/package.json
- demos/default/pages/getStaticProps/[id].js
- demos/default/pages/getStaticProps/withFallback/[...slug].js
- demos/default/pages/getStaticProps/withFallback/[id].js
- demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
- demos/default/pages/getStaticProps/withRevalidate/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
- demos/default/pages/index.js
- plugin/src/templates/getHandler.ts
- test/__snapshots__/index.js.snap
While testing the various rendering modes I made a few changes to the demo pages so that they were easier to test and it was more obvious how each page should be rendered. I thought it might be good to push these changes, if everyone agrees they are useful?
* Added descriptive text at the top of each page with a dynamic path that explains which paths are prerendered and what fallback options are enabled for other slugs
* Made the prerendered paths more consistent (always IDs 1 and 2)
* Added some package scripts for testing with `next build && next start`
* Added a simple VS Code launch.json for attaching the debugging to running inspector process
> feat: dx updates to default demo site

- docs/middleware.md
Adding a little bit of clarification to the docs page on Middleware as it wasn't entirely clear whether the caveats mentioned applied to running the Middleware on edge functions.
I also tried to make sure that info that appeared in the [root README](https://github.com/netlify/netlify-plugin-nextjs#nextjs-middleware-on-netlify) also appeared in this document for consistency.
None needed
> docs: update notes about running Middleware

- plugin/src/templates/edge/ipx.ts
- plugin/src/templates/edge/runtime.ts
- plugin/src/templates/edge/utils.ts
This replaces `netlify:edge` with `https://edge.netlify.com`.
Part of https://github.com/netlify/pillar-runtime/issues/322.
---
> fix: replace netlify:edge identifier with full URL

- plugin/src/templates/edge/runtime.ts
The next plugin doesn't proxy /_next/static/ when request as it gets dropped. This stops chunks from loading when proxied to a different Next.js site.
---
> fix: allow proxy of /_next/static

- package-lock.json
- packages/runtime/package.json
- packages/runtime/src/templates/getHandler.ts
Allows the `getSecretsForBuild` and `getNetlifyGraphTokenForBuild` functionality to work with ISR in next.js.
Populates an environment variable that graph helpers exported from `@netlify/functions` will be able to read.
Here is an example of it in action: https://bucolic-torte-c9a71a.netlify.app/posts/15
Corresponding code: https://github.com/dwwoelfel/nextjs-blog-theme-9/blob/main/pages/posts/%5Bslug%5D.js#L17
---
> feat(graph): populate graph token for ISR

- packages/runtime/src/helpers/files.ts
- packages/runtime/src/index.ts
As part of the build process, we patch the next server files to enable certain features. Currently we unpatch the files after the build, to keep things clean. However this means they're not patched when running `ntl dev`. This is a problem if we want to run middleware, which needs the patch to be enabled.
This PR changes it so that the files aren't unpatched. Instead we ensure that if the file has been patched that we use the unpatched version when applying the patch again.
1. Ensure the site builds and that middleware works
---
> chore: retain patched server files

- package-lock.json
- packages/runtime/package.json
- packages/runtime/src/helpers/utils.ts
- packages/runtime/src/index.ts
- test/index.js
Reverts https://github.com/netlify/next-runtime/pull/1536, and changes the npm package name to `@netlify/plugin-nextjs` in the package's package.json
> chore: revert skipping runtime, revert package name to plugin-nextjs

- .github/workflows/pre-release.yml
- .github/workflows/release-please.yml
- .github/workflows/test.yml
- demos/next-auth/package.json
- demos/next-auth/pages/_app.tsx
- demos/next-auth/tsconfig.json
- package-lock.json
Update demo from React 17, which broke builds. Also changes tests to run with Node LTS (16) because Node 18 was causing engines issues.
1. Check the next-auth demo preview builds
---
> chore: fix broken next-auth demo

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- demos/base-path/local-plugin/manifest.yml
- demos/base-path/package.json
- demos/custom-routes/package.json
- demos/default/package.json
- demos/middleware/package.json
- demos/next-export/package.json
- demos/nx-next-monorepo-demo/local-plugin/manifest.yml
- demos/plugin-wrapper/package.json
- demos/server-components/package.json
- demos/static-root/local-plugin/manifest.yml
- demos/static-root/package.json
- package-lock.json
We've backed-out the runtime name. This reverts the dependencies in the demos.
1. Ensure all demo sites build
---
> chore: revert runtime dep name in demos

- demos/middleware/netlify.toml
- demos/server-components/netlify.toml
- packages/runtime/src/helpers/edge.ts
- packages/runtime/src/helpers/files.ts
- packages/runtime/src/index.ts
Change edge function to opt-out instead of opt-in. To disable it, they must set NEXT_DISABLE_NETLIFY_EDGE to true. If this is set and the site has middleware it will give a warning saying this is deprecated but won;t fail the build. However if the site has edge functions (i.e. edge runtime) then it will fail the build.
I am asking to merge this before I've written the full tests and updated the docs so that we can get a tagged release out asap. I will follow up with tests. Issue here: https://github.com/netlify/next-runtime/issues/1552
1. Visit the middleware and server components deploy previews
Fixes #1431
---
> feat: default edge middleware to on

- packages/runtime/src/templates/edge/next-dev.js
Instead of importing the NextRequest and NextResponse objects from `next/server`, import them from the individual files. The top-level import was causing problems as Deno was downloading far more than was needed.
> fix: use individual next/server deno imports

- packages/runtime/src/index.ts
Fixes the onBuild error `TypeError: Cannot convert undefined or null to object` when providing a null middlewareManifest, or null middlewareManifest.functions to `Object.keys`. This can happen with Next 11 (no middlewareManifest), and middleware beta (no middlewareManifest.functions)
---
> fix: check for middleware manifest before providing to Object.keys

- packages/runtime/src/helpers/dev.ts
- packages/runtime/src/templates/edge/next-dev.js
Currently when running `ntl dev`, if there isn't any middleware when you start the server and then create one, even though the file is correctly compiled, the middleware isn't imported until a restart because Deno has cached the "fact" that it's missing. It correctly updates any changes if the middleware already exists at the time the server starts.
This PR adds a cache-busting hash to the import URL, which ensures it try to load dynamically on every request.
Published as `@netlify/plugin-nextjs@4.17.1-runtime.4`
1. Install `@netlify/plugin-nextjs@4.17.1-runtime.4` in a new Next.js project
2. start `ntl dev`
3. Add a `middleware.ts`, such as the one below
4. Reload the page and check it works
```typescript
import { NextResponse } from 'next/server'
export async function middleware(req) { …
```
> fix: ensure newly-created middleware works

- .release-please-manifest.json
- package-lock.json
- packages/next/package.json
This is the release of `@netlify/next@1.0.0`. It has already been released to npm, so this is just updating it in the repo. It was manually released because using release-please would release the runtime too.
> chore: release next-v1.0.0

- packages/runtime/src/helpers/utils.ts
- packages/runtime/src/helpers/verification.ts
- test/helpers/verification.spec.ts
Replaces #1569
Allows overriding the function bundle size check. This should only be enabled in consultation with someone from the Netlify support team. If enabled, your deployments may break due to exceeding the maximum size limit on the underlying infrastructure that this check is is raising awareness of.
Build a site with `ntl build` and `DISABLE_BUNDLE_ZIP_SIZE_CHECK` enabled. Should see a warning message about this functionality
> feat: allows disabling function size check

- packages/runtime/src/templates/edge/next-dev.js
Uncommenting this was missed in the launch plan - this solves the immediate issue of the edge function crashing when first running `ntl dev` and then `ntl deploy --build`. There is still other work incoming for the `cli`, but this takes care of the crash.
1. Create a next project, and do a local install of the next runtime (package json and netlify.toml)
2. Run `npm link` in this repo's `packages/runtime` directory
3. In your next project, run `npm link @netlify/plugin-nextjs`
4. In your next project, run `ntl dev`, then cancel out of it
5. In your next project, run `ntl deploy --build`. Wait until it's completed, and view the deployed site - it should show up without a crash message. 
> feat: only run next-dev middleware in dev

- package-lock.json
- packages/next/CHANGELOG.md
- packages/runtime/package.json
Removes Next.js as a peer dependency within the runtime package as at times it was leading to multiple version of Next.js being installed, and incompatible versions being bundled with the functions when the project was using an older version.
Deploy preview: https://ep-next-test.netlify.app/
The https://ep-next-test.netlify.app/api/hello route is an SSR route
Test case provided in issue: https://ep-hbo-clone.netlify.app/movie (this should render correctly, no error)
Fixes https://github.com/netlify/pod-ecosystem-frameworks/issues/220
> fix: remove Next.js as a peer dependency

- .github/workflows/fossa.yml
Switch fossa scan to use the official fossa action. The existing action is broken
> ci: use fossa action

- packages/runtime/src/helpers/edge.ts
Edge utils files have moved, so we need to copy them correctly in the dev function
> fix: correct handling of edge dev utils

- README.md
- cypress/integration/default/dynamic-routes.spec.ts
- demos/default/pages/getStaticProps/with-revalidate.js
- packages/runtime/src/templates/getHandler.ts
As discussed internally, we are currently mixing terminology by referring to non-prerendered dynamic routes as 'ODB' and pre-rendered routes with revalidate as 'ISR'.
This PR standardises our header values and log output to use Netlify terminology: 'ODB' or 'ODB ttl=60'
See updated Cypress tests
> chore: standardise ODB terminology

- demos/default/next.config.js
- test/index.js
The Next.js experimental option to inline critical css uses a dependency called [critters](https://github.com/GoogleChromeLabs/critters) that currently has a [bug](https://github.com/GoogleChromeLabs/critters/issues/103) that is adding noise to the build/function logs when testing the default demo site.
We can disable this option for now as there are no plans to add test coverage.
1. Build the default demo site and bask in the serenity of log output without...
```
6 rules skipped due to selector errors:
.prose :where(hr+*):not(:where([class~=not-prose] *)) -> Cannot read properties of undefined (reading 'type')
.prose :where(h2+*):not(:where([class~=not-prose] *)) -> Cannot read properties of undefined (reading 'type')
.prose :where(h3+*):not(:where([class~=not-prose] *)) -> Cannot read …
```
> chore: disable critical css to avoid upstream bug

- .eslintrc.js
There appears to be a conflict between [`@typescript-eslint/no-extra-semi`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts#L19) (which is part of the [`@typescript-eslint/recommended`](https://github.com/netlify/eslint-config-node/blob/main/.eslintrc.cjs#L389) config) and the prettier rule [`semi: false`](https://github.com/netlify/eslint-config-node/blob/main/.prettierrc.json#L2).
The [prettier rule](https://prettier.io/docs/en/options.html#semicolons) will add a semicolon in the following instance to protect from [ASI failures](https://prettier.io/docs/en/rationale.html#semicolons).
https://github.com/netlify/next-runtime/blob/main/packages/runtime/src/helpers/config.ts#L95
However, the linter then complains because of …
> chore: override semicolon lint rule

- cypress/integration/default/dynamic-routes.spec.ts
We recently updated the ODB handler logging to match the minimum TTL enforced by the ODB function itself, but did not update the Cypress test to match. This PR fixes that.
> test: fix test to match new minimum ODB TTL logging

- package-lock.json
- packages/runtime/package.json
- packages/runtime/src/templates/edge/ipx.ts
- packages/runtime/src/templates/ipx.ts
This PR includes two fixes to validate next/image prarams. First, the ipx edge function ensures that the passed props are valid, returning a 400 error if not. Second, it upgrades `@netlify/ipx` and passes the new `localPrefix` option, to enforce local image sources that start with `/_next/static/`.
Draft because it's waiting to release https://github.com/netlify/netlify-ipx/pull/83
1. Open `/image` in the default site preview. Open the first image and modify any of the params to be non-numeric, and check for the error message
---
> fix: validate next/image params

- packages/runtime/src/templates/getHandler.ts
Next.js uses 307 and 308 codes for its redirects, but our ODB functions currently only invalidate cached content for 200, 301 and 404 codes. This means ISR pages that conditionally return a redirect are not updating as expected.
A fix to Netlify Proxy for the above issue is currently in progress and this PR is a corresponding fix for a specific Next.js case: ISR pages with redirects, but without a `revalidate` value, are returned to the ODB with a default `max-age` of 1 year, which causes the ODB to cache them indefinitely. This PR ensures that redirects without `revalidate` are cached ephemerally for 60s.
~Visit /getStaticProps/with-revalidate-redirect/ on the demo site deploy preview and observe that the page should redirect if the last digit of the current minute is 0-4 and should show …
> feat: cache redirects for 60 seconds if no ttl provided

- packages/runtime/src/helpers/edge.ts
Edge functions now support display names. This PR adds support for these. Aside from the ipx and dev edge funcitons, these just use the name from Next.js, which is the path.
1. Visit a deploy that uses edge functions (e.g. [this one with middleware](https://app.netlify.com/sites/next-plugin-edge-middleware/edge-functions?scope=deployid:634004bb7ee81700098bf533) or [this one with server components](https://app.netlify.com/sites/next-plugin-rsc-demo/edge-functions?scope=deployid:634004bbd73ce8000850da97)
2. View the edge function logs
3. Observe that the list of functions in the filter uses display names (e.g. middleware, next/image handler)
---
> feat: use display names for edge functions

- cypress/integration/middleware/standard.spec.ts
- demos/middleware/pages/api/edge.ts
- package-lock.json
- packages/runtime/src/helpers/edge.ts
Currently Next.js creates a global function in the edge runtime called `__import_unsupported` by defining it as an immutable property on `globalThis`. This means that if there is more than one of these definitions in a single edge function bundle then there is an error when they both try to define it. This PR patches the generated bundle (yeah, I know) to add a check before defining it. I suppose I _could_ try contributing upstream.
The only scenario where this happens now is if you have more than one Next.js edge function or middleware. This means that you need to define an API route to use `experimental-edge` runtime, and also have middleware.
1. Visit the middleware deploy preview
2. Load the edge API page `/api/edge`
---
🧪 Once merged, make sure to update the version if needed and …
> fix: prevent Next from defining duplicate global property in edge functions

- packages/runtime/src/helpers/analysis.ts
With the changes to one function per API route, we try to use static analysis to extract the config. However these tools were only added in Next 12.2, and we weren't handling the case where they are missing. This PR ensures that we gracefully handle the missing modules.
Fixes #1690
> fix: gracefully handle missing static analysis tools

- package-lock.json
- package.json
- packages/runtime/package.json
- packages/runtime/src/templates/handlerUtils.ts
Uses the `follow-redirects` library to make the `http` request for downloading a file from the CDN.
In cases we where needed to follow the redirect initially returned we were instead failing the request, leading to `500` errors regarding missing files as seen in #1679
* Visit https://ep-next-auth-investigation.netlify.app/auth/signin
* Open the network tab
* Confirm that the `signin.json` file request is returning a `200` response (might need to refresh the page
* Click 'sign in'
* The redirect should work as expected and there should be no `500` responses returned
Should be noted that the test site used above came from the [user who reported the issue](https://github.com/Joroze/next-netlify-starter-nextauth/pull/1), I just forked it.
I haven't added automated tests here because I'd be …
> fix: follow redirects when downloading a file from the CDN

- cypress/integration/default/api.spec.ts
- package-lock.json
- packages/runtime/src/templates/getApiHandler.ts
We had previously enabled minimal mode for API routes, because we didn't need routing. However this also disabled custom headers. This PR enables it and adds an e2e test.
1. Visit `/api/hello` in the default demo and check for `'x-custom-api-header': 'my custom api header value'`
Fixes #1712
---
> fix: disable minimal mode for API routes

- cypress/integration/middleware/standard.spec.ts
- demos/middleware/middleware.ts
- package-lock.json
The middleware demo isn't setting a cookie on the `/cookies` route currently because we forgot to add it to the config. 
Fixes #1639
1. Visit the middleware Deploy Preview 
2. Click the "Cookies API" link, or visit `/cookies` 
3. See that the "netlifyCookie" has been set.
---
> fix: add cookies route to middleware config

- cypress/integration/default/images.spec.ts
- demos/default/next.config.js
- demos/default/pages/broken-image.tsx
- demos/default/pages/image.js
- demos/static-root/pages/index.js
- test/index.js
Swaps `next/legacy/image` imports with `next/image` imports. I've also added a test to verify that a broken image due to image configuration in Next.js should error out if the host is not allowed.
All the demo sites should build fine and all the tests should pass.
Closes #1721 
---
> chore: replace next/legacy/image with next/image

- packages/runtime/src/helpers/functions.ts
- packages/runtime/src/index.ts
- test/__snapshots__/index.js.snap
- test/index.js
Now we only create custom rewrites and Edge functions for background and scheduled functions. Prior to this PR, we were splitting all API routes and creating separate functions and rewrites for them. This should decrease build times drastically (back to normal) for folks not using extended API routes (scheduled and background functions), and for those who are, the build time should be what it was plus whatever amount of time it takes to build the functions for the advanced API routes.
From a user facing perspective nothing has changed, so all dmoe sites and their corresponding tests should pass.
As well, the logs for the default demo site deploy preview, https://deploy-preview-1731--netlify-plugin-nextjs-demo.netlify.app/, should only create the following functions (see …
> fix: only split extended routes to decrease build times

- package-lock.json
- packages/runtime/src/helpers/functions.ts
- packages/runtime/src/templates/getPageResolver.ts
- test/__snapshots__/index.js.snap
- test/index.js
`next/server`, in its wisdom, always loads `_app` and `_document`, even in API routes. This PR ensures that any dependencies of these files are included in the API routes bundle.
1. Visit the demo site that is using the published tagged version of this, and check the logs: https://app.netlify.com/sites/next-scheduled-test/functions/_api_scheduled-test-handler
---
> fix: resolve _app deps in API routes

- packages/runtime/src/helpers/config.ts
- test/index.js
Currently we exclude several large node modules from being bundled with functions, to avoid going over the 50MB limit. Since Next 13, functions are trying to bundle swc binaries, which are massive. This PR excludes them. However, some users _do_ want to bundle sharp, for example if they're using it in API call. This PR means it no longer excludes sharp if the user has manually added it to `included_files`
1. Run a local build of the demo site.
2. Run `zipinfo .netlify/functions/___netlify-odb-handler.zip | sort -nr -k 4 | head`. Ensure that no files matching `@next/swc*` are included.
---
> fix: exclude swc by default, and don't exclude sharp if included

- demos/nx-next-monorepo-demo/package-lock.json
- demos/nx-next-monorepo-demo/package.json
- package-lock.json
- packages/runtime/src/helpers/files.ts
- packages/runtime/src/helpers/redirects.ts
- packages/runtime/src/index.ts
- test/__snapshots__/index.js.snap
- test/index.js
Currently we expect Next.js to publish the `distDir` (i.e. `.next`). This is how we ascertain how to find the build files, particularly `required-server-files.json`. However most of the generated outputs are not created in the correct structure, so we need to copy or move them there as part of the build. This has worked fine so far, but has some important drawbacks. The main one is that it means the whole folder is uploaded as part of the deploy, even though most of it is not needed - and in fact needs 404 redirects to avoid making them publicly available. This hasn't been a major problem in the past (once the first deploy has been uploaded there aren't many extra files that need uploading). However Next 13 has started generating very large cache files that change on every build, which …
> fix: publish from subdirectory

- README.md
> chore: add `pnpm` info to README

- packages/runtime/src/templates/getHandler.ts
Occasionally we run into situations where it would be useful to know more about the origin response from the Next server to our handler functions.
This PR writes the origin headers and status code to the function logs when the request includes the header `x-next-debug-logging`.
1. Visit an SSR/ISR page that is routed to a handler function and include the above request header
2. Observe the origin response in the function logs
> feat: add next debug logging

- packages/runtime/src/helpers/files.ts
- packages/runtime/src/helpers/redirects.ts
- packages/runtime/src/index.ts
- test/__snapshots__/index.js.snap
- test/index.js
This reverts #1756. There were issues with the change to publishing from a subdirectory, so we are backing it out for now.
I have not been able to reproduce the failure, so I can't test this as a fix. However it is just a straight revert of the previous change, so should be relatively uncontroversial (famous last words). 
---
> fix: revert publish from subdirectory

- packages/runtime/src/helpers/edge.ts
Last week I added [a polyfill for headers.getAll](https://github.com/netlify/next-runtime/pull/1766). However Next.js has now added a check to the edge function return value to see if it's an instanceof `Response`. This means that our polyfilled version wouldn;t match if the user returned e.g. `Response.redirect`, or `fetch()`. This PR changes the polyfill from a subclass to augmenting the prototype of `Headers`. 😬 
This was caught by the e2e tests PR, but it can be checked for regression by looking at the middleware deploy preview
---
> fix: better headers.getAll polyfill

- .github/pull_request_template.md
- CONTRIBUTING.md
Updates our contributing guidelines to indicate that an issue must first be opened and discussed before submitting a PR.
N/A. This only updates documentation.
Closes #1807
---
> docs: added a link to the contributing guidelines in the PR template

- .eslintignore
- .eslintrc.js
- jestSetup.js
- package-lock.json
- package.json
- packages/runtime/src/templates/ipx.ts
Disables `n/no-missing-import`. This rule isn't needed for TypeScript, and was causing false test failures.
1. Run `npm run format` locally and see that it passes.
---
> chore: fix eslint config

- test/e2e/jest.config.js
Increase the default test timeout to 5 mins, to give time to deploy the demo site
> ci: increase test timeout

- demos/base-path/package.json
- demos/canary/package.json
- demos/custom-routes/package.json
- demos/default/package.json
- demos/middleware/package.json
- demos/next-auth/package.json
- demos/next-export/package.json
- demos/next-with-edge-functions/package.json
- demos/static-root/package.json
- package-lock.json
- package.json
- packages/next/package.json
- packages/runtime/package.json
- test/e2e/modified-tests/middleware-general/test/index.test.ts
Update Next.js to 13.0.7, specifically to resolve `https://github.com/vercel/next.js/issues/43623` which is blocking https://github.com/netlify/next-runtime/pull/1757
> chore: update next to 13.0.7

- demos/default/pages/api/shows/[...params].js
- demos/default/pages/api/shows/[id].js
- demos/default/pages/deep/import.js
- demos/default/pages/getServerSideProps/[id].js
- demos/default/pages/getServerSideProps/all/[[...slug]].js
- demos/default/pages/getServerSideProps/static.js
- demos/default/pages/getStaticProps/[id].js
- demos/default/pages/getStaticProps/static.js
- demos/default/pages/getStaticProps/with-revalidate.js
- demos/default/pages/getStaticProps/withFallback/[...slug].js
- demos/default/pages/getStaticProps/withFallback/[id].js
- demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
- demos/default/pages/getStaticProps/withRevalidate/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
- demos/default/pages/index.js
- demos/default/pages/shows/[...params].js
- demos/default/pages/shows/[id].js
- demos/default/public/shows1.json
- demos/middleware/pages/shows/[id].js
- demos/middleware/pages/shows/static/[id].js
We occasionally run into rate limiting problems with the example API used for demos and testing. This is a particular issue for an upcoming PR that adds more demo pages that need to statically fetch data at build time.
This PR replaces all `api.tvmaze.com` references with our new API proxy at `tvproxy.netlify.app`
All tests on demo sites should run as before.
https://github.com/netlify/tvproxy
> chore: use api proxy for tv maze api

- demos/default/pages/api/shows/[...params].js
- demos/default/pages/api/shows/[id].js
- demos/default/pages/getServerSideProps/[id].js
- demos/default/pages/getServerSideProps/all/[[...slug]].js
- demos/default/pages/getStaticProps/[id].js
- demos/default/pages/getStaticProps/withFallback/[...slug].js
- demos/default/pages/getStaticProps/withFallback/[id].js
- demos/default/pages/getStaticProps/withFallbackBlocking/[id].js
- demos/default/pages/getStaticProps/withRevalidate/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallback/[id].js
- demos/default/pages/getStaticProps/withRevalidate/withFallbackBlocking/[id].js
- demos/default/pages/shows/[...params].js
- demos/default/pages/shows/[id].js
- demos/middleware/pages/shows/[id].js
- demos/middleware/pages/shows/static/[id].js
- package-lock.json
Quick follow-up PR to #1863, incorporating sanitisation of user input to prevent potential SSRF attacks.
> chore: validate user input for tv maze urls

- packages/runtime/src/templates/edge-shared/utils.ts
- test/e2e/modified-tests/skip-trailing-slash-redirect/index.test.ts
When adding the Middleware headers to the response we ended up overriding the cookies set by the API route and returning only the cookies set within middleware. This fix ensures that the cookies set within the Middleware and API route are merged, by using 'append' instead of 'set', and that they are in the correct order. 
Fixes #1797 
---
> fix: merge Middleware and API route response cookies

- packages/runtime/src/templates/getApiHandler.ts
It seems it was copied over when splitting APIHandlers from Handlers, but isn't actually used.
Tests
---
> fix: getMaxAge is not used in APIHandlers

- docs/redirects-rewrites.md
The [current Netlify docs](https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites/#using-rewrites-and-headers-files) mention a `_rewrites` file, but I don't believe such a file actually is supported -- the correct file I believe is `_redirects`
- https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites/#using-rewrites-and-headers-files
- https://github.com/netlify/next-runtime/blob/main/docs/redirects-rewrites.md
> docs: change _rewrites to _redirects in docs

- packages/runtime/src/helpers/edge.ts
- test/matchers.spec.ts
Follow me, if you will, back to the summer of 2022.  Next.js middleware had gone to GA, which included updating the manifest format to include `functions` as well as `middleware`. Shortly after (the next patch release) they added support for middleware matchers, replacing the `regex` key on middleware defintions with an array of matchers, and doing the same for the new functions because why not add a new feature and make a breaking change to a format in a patch release. Anyway, for that brief period in June there was support for functions but no matchers. This PR makes those work.
1. Ensure the new unit tests pass. I'm not adding a demo site for a manifest format that was around for less time than the British prime minister who was running for office at that time. A unit test will have to …
> fix: handle v1 edge function definition

- packages/runtime/src/helpers/edge.ts
- packages/runtime/src/templates/edge/shims.js
- packages/runtime/src/templates/edge/shims.ts
We provide a number of shims and polyfills to make our edge runtime work with Next.js. Currently they're a big string in a helper file. This PR extracts them into a file, meaning they can be properly typechecked.
This should have no effect on the output.
---
> refactor: extract edge runtime shims into separate file

- .github/workflows/pre-release.yml
GitHub is [deprecating the `set-output` workflow command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) in actions after 31st May 2023.
This PR changes the GitHub workflow to use the new format. 
1. Check that the PR actions work as expected with a pre-release
---
> fix: change deprecated set-output github actions

- test/e2e/jest.config.js
Ups the e2e timeout to 10 minutes instead of 5.
> chore: up test timeout

- .github/ISSUE_TEMPLATE/bug_report.yml
Updates the issue template to explicitly ask if the issue is related to `app` dir or not.
Close #1947
N/A
---
> chore: updated issue template

- packages/runtime/src/templates/edge/next-dev.js
Removes the `Deno.stat` call from the dev edge function.
It rethrows any errors besides the Module not found error for the `middleware.js` file. 
Because we have a number in the hash of the import it is also super easy to see if this error is from our import or not.
Fixes https://github.com/netlify/pod-ecosystem-frameworks/issues/422
---
> fix: remove fs access which isn't available in edge functions

- packages/runtime/src/templates/edge/next-dev.js
The id in the import and in the catch was different. Now they are the same.
> fix: use the same id for importing and checking error

- packages/runtime/src/templates/edge/next-dev.js
Some async business is messing with the idx value, where it's idx=z (strangely 1 more than we'd expect) when entering the catch condition, but idx=z-1 (correct value) when comparing in the if statement in the catch. 
We know that the correct values are being used when comparing, and the value of the middleware.js#x doesn't matter when the catch occurs, we just want to return silently. 
Fixes https://github.com/netlify/next-runtime/issues/1983
---
> fix: make error message matching more generic

- packages/runtime/src/helpers/config.ts
- packages/runtime/src/helpers/edge.ts
While looking into https://github.com/netlify/pod-ecosystem-frameworks/issues/376 I searched for the usage of `IMAGE_FUNCTION_NAME` as the other constants showed all their usages. We had a couple of instances where we used `_ipx` instead of the constant and thus couldn't find it immediately.
So this is a small QoL PR to use the constant in all relevant places.
> fix: use `IMAGE_FUNCTION_NAME` constant

- package-lock.json
- package.json
- packages/runtime/src/constants.ts
- packages/runtime/src/helpers/config.ts
- packages/runtime/src/helpers/functions.ts
- packages/runtime/src/helpers/functionsMetaData.ts
- test/functionsMetaData.spec.ts
This update creates a metadata file that will allow us to update the naming of our generated functions within the UI and will help us keep track of the nextjs-runtime versions being used.
We ran into some errors within the previous PR that were seemingly unrelated to our changes and transferred everything over. 
Prev: https://github.com/netlify/next-runtime/pull/1973
closes https://github.com/netlify/pod-ecosystem-frameworks/issues/407
closes https://github.com/netlify/pod-ecosystem-frameworks/issues/376
1. Within the Netlify UI go to the demo site and go to the Functions tab 
2. In the Functions search bar enter 1999 for the repo
3. Should see Next.js SSR handler, Next.js ISR handler, and next/image handler
1. Should be able to see the version being returned within …
> feat: add generator meta data for framework generated Netlify Functions

- cypress/integration/default/appdir.spec.ts
- packages/runtime/src/templates/edge-shared/rsc-data.ts
~Fixes an issue where requests coming in to the edge function that were handling React Server Components were always returning the first cached response causing issues with serving the content type `text/html` or `application/octet-stream`~
It looks like the `vary` header is already in the response, so I've added tests to ensure it remains.
Closes https://github.com/netlify/pod-ecosystem-frameworks/issues/352
There is an end-to-end test in this PR that tests that this works, but you can also curl the deploy preview to see it working.
1. Run `curl -v https://deploy-preview-1993--netlify-plugin-nextjs-demo.netlify.app/blog/erica/`. The content type returned is `content-type: text/html; charset=utf-8`
2. Run `curl -v -H "RSC: 1" https://deploy-preview-1993--netlify-plugin-nextjs-demo.netlify. …
> test: added tests to check that the vary header contains 'RSC'

- .github/workflows/test.yml
The scheduled tests run fails consistently due to incorrect syntax in the workflow.
This is due to the `group: {{github.head_ref}}` reference being blank if the workflow isn't executed from a pull request.
[Test workflow](https://github.com/netlify/next-runtime/blob/92e209f177312d4c4e6b64f8feb6c80670e46d8d/.github/workflows/test.yml#L11)
```
concurrency:
group: ${{ github.head_ref }}
cancel-in-progress: true
```
This PR adds a default fallback which is guaranteed to be unique and defined for the run.
See: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
Fixes netlify/pod-ecosystem-frameworks#434
1. Ensure that the PR tests still runs
2. Verify that the nightly tests now runs without failure
---
> fix: add fallback ID for scheduled test run

- cypress/integration/default/appdir.spec.ts
For some reason the `Vary` header tests for `RSC` are failing now and blocking other PRs. I'm skipping them for now. I'm going to revisit the issue associated issue.
The revert is only tests that were failing so nothing to test.
https://github.com/netlify/pod-ecosystem-frameworks/issues/352
---
> test: skip tests to check for vary header containing 'RSC' 

- cypress/integration/default/appdir.spec.ts
- packages/runtime/src/templates/edge-shared/rsc-data.ts
- test/rsc-data.spec.ts
Types in the project were not up to day and 
Closes #1940
1. Ensure the deploy previews are green.
2. There are tests that cover this fix.
---
> fix: routes with null data routes can be filtered now

- packages/runtime/src/templates/edge-shared/rsc-data.ts
- test/rsc-data.spec.ts
There was a TypeScript error that was not picked up as we copy them for the build. I've added some tests to cover this like we did in #2018.
Closes #1940
1. Ensure the deploy previews are green.
2. There are tests that cover this fix.
---
> fix: now data routes for dynamic routes filter even when null when creating the RSC data router

- packages/runtime/src/helpers/edge.ts
- test/edge.spec.ts
In #1940 and #2041 we fixed an error that was occurring because the `rsc-data` edge function was unable to handle `null` `dataRoutes` in the `prerender-manifest.json`. However, the problem of null data routes also affected our own `.netlify/edge-functions/manifest.json` because the edge functions bundler always [expects a string](https://github.com/netlify/edge-bundler/blob/c91593f5e7f0831e4cfe3c69d240d6044c8869c8/node/manifest.ts#L171).
This PR adds a condition so that appDir routes with falsy dataRoutes are not added to the edge manifest (and thus will not invoke the `rsc-data` edge function, which is the expected result).
Tests added for the `writeRscDataEdgeFunction`
> fix: ensure appDir routes with null dataRoutes are not added to edge manifest for rsc-data

- .github/workflows/e2e-next.yml
Makes our e2e tests run on a daily schedule. 
I'd like to add slack notifications, but am waiting on info.
> test: move e2e tests to a daily schedule

- packages/runtime/src/helpers/files.ts
In v13.3.0, Next.js shipped a [change](https://github.com/vercel/next.js/pull/46801) that removed the `target` parameter from the Next config object. It was deprecated in Next 12 (and its usage [discontinued](https://github.com/vercel/next.js/pull/41495) in 12.3.2), but this recent change means the value is `undefined` instead of defaulting to `server`, which causes our Runtime to not find any static files to move to the CDN.
This PR simply flips the logic so that 'server' is the default instead of 'serverless'. This works because the default directory for static files is `.next/server`.
Tests should pass as before.
Fixes #2043 
---
> fix: default to target: server, not serverless

- .github/workflows/cypress-canary.yml
- .github/workflows/cypress-demo-nx.yml
- .github/workflows/cypress-demo-static.yml
- .github/workflows/cypress-demo.yml
- .github/workflows/cypress-middleware.yml
We unnecessarily parallelize our Cypress tests when actually a lower `matrix` is needed or no parallelization at all. This PR fixes that.
I also noticed that GitHub actions complained about unknown `headless` arg - it doesn't exist on the action since it runs headless by default. So I just removed it.
> chore: Optimize Cypress parallelization

- renovate.json
In order for us to not get outdated with the `next` version, tell renovate to update it.
Fixes https://github.com/netlify/pod-ecosystem-frameworks/issues/468
> chore: Add `next` dep to renovate config

- .github/workflows/cypress-canary.yml
- .github/workflows/cypress-demo-nx.yml
- .github/workflows/cypress-demo-static.yml
- .github/workflows/cypress-demo.yml
- .github/workflows/cypress-middleware.yml
- .github/workflows/e2e-appdir.yml
- .github/workflows/e2e-next.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-please.yml
- .github/workflows/test-deno.yml
- .github/workflows/test-integration.yml
- .github/workflows/test.yml
This makes use of the correct concurrency setting as explained here: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
This also updates the checkout and setup-node actions which were out of date.
> chore: update github workflows

- packages/runtime/src/helpers/functions.ts
- packages/runtime/src/index.ts
- packages/runtime/src/templates/getApiHandler.ts
- packages/runtime/src/templates/getHandler.ts
- packages/runtime/src/templates/server.ts
Follow-up, addresses the comments from https://github.com/netlify/next-runtime/pull/2058#discussion_r1192550151.
---
> fix: follow-up to split-api revalidate behaviour

- .github/workflows/cypress-canary.yml
- .github/workflows/cypress-demo-nx.yml
- .github/workflows/cypress-demo-static.yml
- .github/workflows/cypress-demo.yml
- .github/workflows/cypress-middleware.yml
Currently the e2e tests are not run on master, because the paths in the workflow are incorrect.
> chore: fix path for e2e tests

- packages/runtime/src/templates/edge-shared/utils.ts
- packages/runtime/src/templates/edge/next-dev.js
As explained in https://github.com/amannn/next-intl/issues/290#issuecomment-1549110801 it seems that both a named `middleware` export and a `default` export is supported.
This allows both for `netlify dev` when we import the middleware.
N/A
No tests were added but I tried the change manually on the repository shared in https://github.com/netlify/next-runtime/issues/2106
1. Existing E2E middleware should continue to work
2. https://github.com/netlify/next-runtime/issues/2106
Fixes https://github.com/netlify/next-runtime/issues/2106
> fix: support named & default export for middleware in ntl dev

- packages/runtime/src/templates/getApiHandler.ts
This PR fixes a regression introduced in https://github.com/netlify/next-runtime/pull/2058. `clientContext` isn't available in backround functions, so destructuring on it throws an error.
1. TODO
> fix: clientContext isn't available in background functions

- packages/runtime/src/helpers/functions.ts
If the Next Runtime is auto-installed, then `follow-redirects` (which is a dep of `next-runtime`) won't be resolvable from `.next` (the `publish` dir). This results in an error.
To fix this, I'm adding `__dirname` as a second resolution starting point. `__dirname` always points to a file within the `next-runtime` package, so `follow-redirects` should be resolvable from there.
Previously discussed in https://netlify.slack.com/archives/C02T8ASK2E9/p1684318093610159.
1. TODO
> fix: resolve follow-redirects from runtime package

- packages/runtime/src/templates/edge-shared/utils.ts
In some instances `response.cookies._headers` was `undefined` even though the types say they're not supposed to be causing the check introduced in #2027 to crash. Now we check if `response.cookies._headers` is defined before doing any operations on it.
1. There are already E2E tests in place from #2027 
Non-standard implementation of ResponseCookies, https://github.com/vercel/next.js/blob/de08f8b3d31ef45131dad97a7d0e95fa01001167/packages/next/src/compiled/@edge-runtime/cookies/index.js#L158
Closes https://github.com/netlify/pod-ecosystem-frameworks/issues/475
> fix: checks when Next.js' implementation of ResponseCookies._headers is undefined now

- packages/runtime/src/constants.ts
- packages/runtime/src/helpers/files.ts
- packages/runtime/src/helpers/redirects.ts
- packages/runtime/src/helpers/utils.ts
- packages/runtime/src/index.ts
- test/__snapshots__/index.spec.ts.snap
- test/e2e/next-test-lib/next-modes/next-deploy.ts
- test/helpers/utils.spec.ts
- test/index.spec.ts
Current strategy of hiding metadata files (creating redirects to 404) has a flaw - redirects are case sensitive, but CDN is not so that means we can still actually reach those files by messing with route casing.
As example `/trace` is supposed to be hidden - and initially it appears to be: https://netlify-plugin-nextjs-demo.netlify.app/trace, however https://netlify-plugin-nextjs-demo.netlify.app/tRace allow to view the `trace` file. Preview Deploy for this PR actually make it impossible to serve that asset regardless of casing as it's just not deployed to CDN: https://deploy-preview-2104--netlify-plugin-nextjs-demo.netlify.app/tRaCe/
This PR changes "hiding metadata files" implementation to actually prevent those files from being deployed by deleting them after all the functions bundling …
> fix: don't deploy metadata files to CDN

- packages/runtime/src/helpers/config.ts
- packages/runtime/src/helpers/flags.ts
- packages/runtime/src/index.ts
- test/index.spec.ts
We discovered that the Split-API-Routes behaviour introduced in #2058 depends on Next.js v12+. Because our Next Runtime needs to support everything from v10 up, I'm adding an additional guard that ensures versions sub v12 continue to use the current behaviour.
1. TODO
> fix: guard split api routes behaviour by next version

- packages/runtime/src/constants.ts
- packages/runtime/src/helpers/functions.ts
- test/__snapshots__/index.spec.ts.snap
- test/helpers/functions.spec.ts
- test/index.spec.ts
This PR updates how API Routes are named + displayed when the Split-API-Routes flag is enabled.
Before, the generated API-Routes were named `_api-0` to `_api-n`, and there were no display names. Now, the names are a bit more complicated, but easier to understand as well. They take into account that some lambdas serve multiple API routes, while others serve only a single one.
In the new logic, those "singleton lambdas" are named [based on their page name](https://github.com/netlify/next-runtime/blob/cbcdc0c25af3b5f5805622b2dab6cfa3c691789c/packages/runtime/src/helpers/utils.ts#L20) (`/api/shows/[:id]` becomes `_api_shows_id-handler`) and receive a display name that shows their route (`Next.js API handler /api/shows/[:id]`). Scheduled functions and background function have that exact same …
> feat: provide display name for split api routes

- cypress/e2e/default/api.cy.ts
- packages/runtime/src/helpers/config.ts
We discovered that dynamic API routes, e.g. `/api/shows/[id].js`, aren't bundled correctly. This is likely due to the square brackets being interpreted as special glob patterns, resulting in the underlying files not being included correctly.
This PR adds an e2e test that demonstrates the bug, and then fixes it by processing the glob patterns before passing them to the build process.
1. TODO
https://github.com/netlify/pod-dev-foundations/issues/516
> fix: bundle dynamic API routes correctly with split-api-routes

- packages/runtime/src/templates/server.ts
The previous Next 13.4 [update PR](https://github.com/netlify/next-runtime/pull/2080/) introduced a route check to optionally use the prebundled react module, as required by Next.
This PR makes it backwards-compatible with Next 11.
Automated tests for previous Next versions are currently in discussion.
> fix: optionally chain server functions when selecting react version

- cypress/e2e/middleware/standard.cy.ts
- demos/middleware/middleware.ts
- demos/middleware/next.config.js
- demos/middleware/pages/locale-test.js
- packages/runtime/src/templates/edge-shared/utils.ts
- packages/runtime/src/templates/handlerUtils.ts
- packages/runtime/src/templates/server.ts
This looks to address issue with `locale` not being set correctly (or at least not in the same way as `next build` + `next start` behaves) when there is rewrite happening in middleware which in turn cause weirdness with client-side routing.
Added a test case to cypress tests
> fix: preserve original path after middleware rewrite

- .github/workflows/add-to-project.yml
- packages/runtime/src/templates/requireHooks.ts
- packages/runtime/src/templates/server.ts
Fix to ensure that the default React module resolution is always used as a fallback when rendering Page Router routes.
This PR also guards against missing module paths in previous versions of Next by try/catching each call to `require.resolve()`.
In addition, this PR fixes a case where paths with query strings caused the route matching to fail.
> fix: edge cases for custom react module resolution

- packages/runtime/src/templates/server.ts
- test/templates/server.spec.ts
During the upgrade to Next 13.4 we implemented a fix so that the correct prebundled version of React is chosen when the route is App vs Pages router. However, we were attempting to determine the type of route using a custom path matching algorithm and it was failing when the route used route groups.
This PR uses the Next native `getAppPathRoutes` function to normalize the route, removing route groups and other artifacts in the path.
Unit tests have been added (and former tests restored as these were yet to be re-enabled after #2080 was merged).
Fixes netlify/pod-ecosystem-frameworks#489 (again)
> fix: use native path matching for prebundled react conditional

- cypress/e2e/middleware/preview.cy.ts
- demos/middleware/middleware.ts
- demos/middleware/pages/api/enterPreview.js
- demos/middleware/pages/api/exitPreview.js
- demos/middleware/pages/index.js
- demos/middleware/pages/previewTest.js
- packages/runtime/src/templates/server.ts
This change make `next-server`'s `runMiddleware` no-op in lambdas. There are some scenarios where `next-server` would attempt that (example one seems to be rendering page in preview mode). The middleware is executed at the edge so executing it at lambda would cause:
- it to run twice causing unknown effects
- rather unknown behavior and support for various middleware APIs (geo? text rewrite)
- crash when using `@netlify/next` enhanced middleware as that would execute in Nodejs env which cause early bail because it's not Deno env.
- when SPLIT_* (api / render ) mode is enabled in next runtime we would not bundle required files to run middleware (common missing module is `.next/server/edge-runtime-webpack.js` and middleware module itself) - we could bundle those but because of all of above …
> fix: don't ever execute middleware in lambda

- package.json
- packages/runtime/src/helpers/edge.ts
- packages/runtime/src/helpers/functions.ts
- packages/runtime/src/index.ts
- packages/runtime/src/templates/getPageResolver.ts
Changes the function path resolution logic to account for the new `packagePath` property, such that functions are placed in the `.netlify/functions-internal` directory inside the package path and not at the repository root.
- https://github.com/netlify/build/pull/5223
- https://github.com/netlify/build/pull/5225
> feat: support new monorepo setup

- packages/runtime/src/helpers/edge.ts
Fixes an issue with monorepos and the new `appDir` where the `packagePath` was not passed down to the RSC edge manifest
I've deployed this change here on my test site with monorepo settings turned on, and the `content-type` is correctly set to `text/x-component`
```
curl -i -H "RSC: 1" https://lukas-next-runtime-demos-default.netlify.app/blog/erica/
```
1. TODO
> fix: pass packagePath down to rsc edge manifest

- package-lock.json
- package.json
CI is having troubles running cypress currently and I think https://github.com/cypress-io/cypress/issues/27915 is issue we are facing, so this tries to bump cypress to be `>12.15.0` as https://github.com/cypress-io/cypress/issues/27915#issuecomment-1737288722 suggests 🤞 (there is version 13 already out, but https://github.com/netlify/next-runtime/pull/2296 which bumps to it shows failing tests, so at least some migration would be needed - I just bump to latest of same major we are already on)
1. TODO
> chore: bump cypress to latest v12

- packages/runtime/package.json
- packages/runtime/patch-import-map.mjs
- packages/runtime/src/helpers/edge.ts
Closes https://linear.app/netlify/issue/FRA-53/netlify-dev-fails-to-run-middleware.
In https://github.com/netlify/next-runtime/pull/2302, we started vendoring Deno dependencies, but we forgot about copying them over for local dev. This PR fixes that.
The main change is a one-liner, but there was a problem within the way `esm.sh` bundles these two dependencies, and the way we import them via `../vendor`:
https://github.com/netlify/next-runtime/blob/5d71bfbba214e88cf59ed335a786806c947a2109/packages/runtime/src/templates/edge/next-dev.js#L1-L2
This was fixed by registering the `import_map.json` created by Deno for local dev.  There was a bug in how that works though, that was only fixed in a [recent release](https://github.com/netlify/cli/releases/tag/v16.8.0) of the CLI. This means …
> fix: copy `vendor` over for local dev

- cypress/e2e/middleware/standard.cy.ts
- demos/middleware/middleware.ts
- packages/runtime/src/templates/edge-shared/utils.ts
Fixes a bug where we were following the redirects returned by a rewritten page.
fixes a bug, no docs needed
added an e2e test.
https://linear.app/netlify/issue/FRA-297/ensure-that-nextresponserewrite-rewrites-instead-of-redirecting
> fix: don't follow redirects for rewrites

- e2e-report/components/table.js
- e2e-report/utils/data.js
In https://github.com/netlify/next-runtime/pull/2489 we rewrote the e2e report. This introduced a bug where test suite links lead to a 404.
N/A
1. Click on a test suite name [here](https://66799b75b078eb00a9e251cc--runtime-e2e-report.netlify.app/) and get a 404.
2. Click on a test suite name [here](https://6679a428bad5990bfcd13197--runtime-e2e-report.netlify.app/) and see the test suite source. (This one is from this branch.)
N/A
> chore(e2e): fix links to test source in new e2e report

- .github/workflows/e2e-report.yml
We run the next.js repo e2e tests every day at 3am UTC but we were running the e2e report (which pulls the artefacts from the e2e workflow) every Wednesday at 3am UTC. We might as well defer it slightly and pull the data from the freshest run.
In addition, since we weren't filtering on run status, it was almost always failing since the e2e report workflow queried for the most recent e2e test workflow run and, if it had already started, would fail to find its artefacts (because it had started but not completed). Here's an [example failed run](https://github.com/netlify/next-runtime/actions/runs/9672892979/job/26685969360). I fixed this by adding the missing status filter.
N/A
I tested the `gh` commands locally.
> ci(e2e): run e2e report cron after e2e tests finish

- CONTRIBUTING.md
Mention the need for locally building Next.js before running the next.js repo e2e tests locally.
N/A - this is documentation
N/A
> docs: mention next.js build in e2e testing instructions

- tests/e2e/simple-app.test.ts
The recent Durable Cache rollout on the platform changed the contents of this header. This test is failing on `main` ([example failure](https://github.com/netlify/next-runtime/actions/runs/9782209033/job/27008026247?pr=2526)).
N/A
N/A - test fix
> chore: update e2e `cache-status` assertion

- src/run/handlers/server.ts
- src/run/headers.test.ts
- src/run/headers.ts
- tests/e2e/durable-cache.test.ts
- tests/integration/run/server-handler.test.ts
- tests/utils/create-e2e-fixture.ts
- tests/utils/fixture.ts
👁️‍🗨️  **This will be easier to review commit by commit:**
- 287177af194b16003af43df9b309c19d0ea13d76 test: add missing unit test coverage for route handler headers
- a8d8fcaf4bae0b896b0f4e595e95e17b8e897e4c feat: specify `durable` cache-control directive if feature flag is enabled for request
- 4bd24ffe7e2152e29ae7887e21e9385e39ac6c69 feat: specify durable cache-control directive
This is gated behind a feature flag for now.
I can't link to any public docs yet, but by the time you're reading this you should be able to find a section on "Durable caching" at https://docs.netlify.com.
This functionality is now documented at https://docs.netlify.com/platform/caching/#durable-directive.
This PR adds exhaustive unit tests and an e2e integration test deployed to a site with the feature flags …
> feat: use Netlify Durable Cache

- src/build/functions/edge.ts
- src/build/functions/server.ts
- src/index.ts
Alternative to https://github.com/netlify/next-runtime/pull/2511
This doesn't fully solve the problem as it can still happen with CLI (it does reduce reach of the problem), but feels much safer than previous PR. This relies on fact that builds on platform don't restore functions generated by previous builds therefore there is no need to clear those dirs. It also moves dir clearing to earlier stage so it's less likely that other integrations produced any functions yet (in case of using CLI)
1. TODO
> fix: only clear stale functions with build through CLI

- .github/workflows/test-e2e.yml
The minimum supported version for canary got bumped recently: https://github.com/vercel/next.js/pull/67274.
We could set different versions per next.js version but it probably isn't worth it here.
N/A
Here's a manual run that proves this fixes it: https://github.com/netlify/next-runtime/actions/runs/9898568341. (You have to inspect the results to see we're back closer to ~99% than to 7%...)
N/A
> test: fix next.js repo e2e tests for canary.56

- .github/workflows/e2e-report.yml
- .github/workflows/test-e2e.yml
This replaces the hardcoded Next.js "latest" version with an optional selector input.
While I was at it, I clarified some confusing aspects of this setup. It's tripped up multiple people already.
N/A
When you make changes to a manual workflow setup, you can't see it reflected in the UI until you merge. However, I was able to use the GitHub CLI to manually trigger workflows against this branch's version of the workflow and it worked:
```sh
gh workflow run -r ci/read-correct-e2e-results-file e2e-report.yml
gh workflow run -r ci/read-correct-e2e-results-file e2e-report.yml -f version=canary
```
This resulted in these runs, respectively:
- https://github.com/netlify/next-runtime/actions/runs/9895424607
- https://github.com/netlify/next-runtime/actions/runs/9895445211
N/A
> ci(e2e-report): support generating report site for version other than latest

- src/build/content/server.ts
- src/build/functions/server.ts
- src/build/plugin-context.ts
- tests/e2e/simple-app.test.ts
- tests/fixtures/simple/app/api/cjs-file-with-js-extension/bundled.cjs
- tests/fixtures/simple/app/api/cjs-file-with-js-extension/route.js
- tests/fixtures/simple/cjs-file-with-js-extension.js
- tests/integration/simple-app.test.ts
We are setting entire request handler function dir as `type: 'module'` right now, which result in `ERR_REQUIRE_ESM` kind of errors when `.js` file which is actually CJS is being required.
Integration and e2e test added using same fixture - both fail. Integration test output https://github.com/netlify/next-runtime/actions/runs/9992611474/job/27618021931?pr=2549#step:12:151 showing `ERR_REQUIRE_ESM` error (e2e only see 500 status, as error is hidden in function logs).
Second commit makes them pass.
> fix: apply type: module only to runtime modules

- tests/netlify-deploy.ts
> test: pack and install runtime when running Next.js e2e tests

- tests/utils/fixture.ts
Ref: https://github.com/netlify/next-runtime/actions/runs/10050411516/job/27778277122?pr=2552#step:12:211 - attempting to fix tests setup for next@canary
1. TODO
> test: adjust setup for next@canary

- edge-runtime/lib/next-request.ts
- edge-runtime/lib/util.ts
- edge-runtime/middleware.ts
- src/build/functions/edge.ts
- tests/fixtures/middleware-conditions/middleware.ts
- tests/integration/edge-handler.test.ts
Scaled down version of https://github.com/netlify/next-runtime/pull/2548 which just adjusts what is being passed to matcher leaving everything else as-is
1. TODO
> fix: edge-middleware i18n matching

- src/index.ts
- tests/e2e/export.test.ts
- tests/fixtures/output-export/app/image/local/page.js
This adds `next/image` support for static exports (we already have it working for regular builds, this just applies needed rewrites and possibly remote image patterns for static export case)
Added e2e test case for static export using next/image (failing in first commit, passing in second)
https://linear.app/netlify/issue/FRP-810/nextjs-output-export-also-disabled-image-cdn
> feat: support next/image with static exports

- src/build/functions/edge.ts
- tests/fixtures/middleware/next.config.js
Custom user webpack config can result in middleware being chunked. Our middleware wrapper assumes unchunked case and will fail at edge function bundling step if it is chunked and result in user facing error like this:
> Cannot read properties of undefined (reading 'default')
Minified generated code for chunked case looks like this:
```
(_ENTRIES="undefined"==typeof _ENTRIES?{}:_ENTRIES)["middleware_middleware-7410c3f3"]=n}]);
//# sourceMappingURL=middleware-7410c3f3.js.map
export default _ENTRIES["middleware_middleware"].default;
```
And middleware manifest looking like this (relevant subset of it) :
```
"middleware": {
"/": {
"files": [
"prerender-manifest.js",
"server/edge-runtime-webpack.js",
"server/middleware-f3956634.js",
"server/middleware-8bfe7224.js", …
```
> fix: handle cases of chunked middleware

- tests/e2e/cli-before-regional-blobs-support.test.ts
- tests/e2e/page-router.test.ts
- tests/e2e/simple-app.test.ts
- tests/integration/static.test.ts
[v14.2.10](https://github.com/vercel/next.js/releases/tag/v14.2.10) and [v15.0.0-canary.147](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.147) included https://github.com/vercel/next.js/pull/69802 which added `private` back into `no-cache,no-store` `cache-control` headers in some cases.
There are still failures after this fix but they are caused by two (three?) additional unrelated issues.
N/A
N/A
N/A
> test(e2e): fix failures due to latest and canary releases

- src/run/headers.test.ts
- src/run/headers.ts
- tests/integration/cache-handler.test.ts
- tests/integration/fetch-handler.test.ts
- tests/integration/simple-app.test.ts
We are currently not applying `durable` directive when serving stale responses which cause issues with updating durable cache
Updated test assertions
Fixes https://linear.app/netlify/issue/FRP-1320/add-missing-durable-directive-for-stale-responses
> fix: use durable cache for stale responses

- playwright.config.ts
- src/run/handlers/cache.cts
- tests/e2e/on-demand-app.test.ts
- tests/e2e/page-router.test.ts
- tests/fixtures/page-router-base-path-i18n/pages/products/[slug].js
- tests/fixtures/page-router/pages/products/[slug].js
- tests/fixtures/server-components/app/api/on-demand-revalidate/path/route.ts
- tests/fixtures/server-components/app/api/purge-cdn/route.ts
- tests/fixtures/server-components/app/product/[slug]/page.js
- tests/integration/cache-handler.test.ts
- tests/integration/static.test.ts
Fixes https://linear.app/netlify/issue/FRB-1352/handle-non-ascii-characters-in-cache-tag-headers
Handles non ASCII characters in cache-tag headers by URI encoding them (does not encode / or valid characters just the non ASCII ones)
Added e2e test case for cacheable page router pages with non-ascii paths
1. TODO
> fix: handle non ASCII characters in cache-tag headers

- src/build/advanced-api-routes.ts
For some reason functions manifest we use to inspect api routes to see if advanced api routes are used stopped working correctly (it just is empty manifest - file is still written out). So I added alternative way to gather api functions that we actually used to use in next-runtime@4 ( https://github.com/netlify/next-runtime/blob/v4/packages/runtime/src/helpers/functions.ts#L546-L547 )
This is fixing currently failing test for next@canary ( https://github.com/netlify/next-runtime/actions/runs/11251896442/job/31283941693 being example)
https://linear.app/netlify/issue/FRB-1379/next-runtime5-with-nextcanary-no-longer-throws-when-advanced-api
> fix: use alternative way of gathering api functions to anaylze

- src/run/handlers/server.ts
- src/run/headers.test.ts
- src/run/headers.ts
- tests/integration/simple-app.test.ts
There are a number of routes ending in `.php` that are commonly probed by bots looking for security vulnerabilities. This PR ensures that the Runtime caches any 404 response resulting from a request to a URL ending in `.php`.
It is designed to help stop excessive function invocations and is a interim solution until we are able to constrain the paths that the SSR function runs on (waiting for regex support).
Integration tests added
Partial solution for FRB-1344
> feat: cache 404s indefinitely for bot probes

- .github/workflows/test-e2e.yml
The latest Ubuntu (24.04) doesn't work out of the box with older versions of playwright.
next@latest and next@canary have been updated: https://github.com/vercel/next.js/pull/71312.
13.5.1 has not been, so let's keep using 22.04 just for that
> ci: fix next.js repo tests workflow for 13.5.1

- e2e-report/package-lock.json
- e2e-report/package.json
We only install this pseudo-monorepo-package's deps in the e2e report CI workflow, not the root deps.
Follow-up to https://github.com/netlify/next-runtime/pull/2673.
> chore(deps): add netlify-cli dev dep to e2e-report/

- .github/workflows/test-e2e.yml
Since it doesn't run on all PRs, I didn't notice it needed a slightly different config when I changed this in https://github.com/netlify/next-runtime/pull/2673.
This workflow checks out next-runtime in one directory and next.js in another, so we need to specify a working directory.
> ci: fix test-e2e workflow

- .github/workflows/test-e2e.yml
Our setup to run Vercel's tests seems to no longer work as expected now that `rc` version is not marked as "prerelease" in Github Releases (we are relying on `prerelease` status of Github release to select git tag for `latest` and `canary` right now).
See https://github.com/netlify/next-runtime/actions/runs/11432475420/job/31803013304 which is supposed to run against `latest` but it checks out following git tag `note: switching to 'refs/tags/v15.0.0-rc.1'.` and later tries to install swc binaries for actual stable ( `pnpm add --workspace-root @next/swc-linux-x64-gnu@14.2.15`) so we might have some problems caused by version mismatch that our current setup is producing.
This changes so we use `npm` as sole source of truth and construct git tag from it instead (basically now git tag is …
> ci: don't use next's github releases as source of most recent stable/canary versions

- tests/utils/next-version-helpers.mjs
New canaries (i.e. `15.0.1-canary.1`) are not matching on our version constraints that use prerelease selector like `nextVersionSatisfies('>=15.0.0-canary.187')` right now - see https://github.com/netlify/next-runtime/actions/runs/11454176059/job/31867886319 - this adjust version constraint check to allow those to match by using `includePrerelease` flag ( see https://www.npmjs.com/package/semver#prerelease-tags )
1. TODO
> ci: use includePrerelease flag for version checks

- .github/pull_request_template.md
- .github/workflows/e2e-report.yml
- .github/workflows/test-e2e.yml
- CONTRIBUTING.md
- README.md
- package.json
- run-local-test.sh
- tests/netlify-deploy.ts
- tests/utils/create-e2e-fixture.ts
- tests/utils/fixture.ts
- tests/utils/helpers.ts
- tools/build.js
This is subset of changes from https://github.com/opennextjs/opennextjs-netlify/pull/2693 which aim to handle just GitHub repository adjustments:
repo: netlify/next-runtime → opennextjs/opennextjs-netlify
Note https://github.com/opennextjs/opennextjs-netlify/compare/tmp/test...tmp/test2 is the rest of changes from above PR
N/A
> chore: handle repo rename

- .github/workflows/test-e2e.yml
- run-local-test.sh
- tests/netlify-deploy.ts
- tests/test-config.json
- tools/deno/junit2json.ts
This is grab-back of various improvements for running Vercel tests:
- we are now able to collect build logs which mean we should no longer NEED to skip those tests to prevent failures that are only related to CLI and not actual functionality not working - if the test is testing just the output - it makes sense to skip it to avoid wasting time on test that is not actually testing anything related to Netlify (I actually do skip one of those here, despite the test now passing)
- we are able to recognize if test is using Canary only feature ( https://github.com/vercel/next.js/issues/71307 ) and skip processing results if that was cause for build/deploy failure as this test is just not applicable to stable Next versions
- lower shards we use after move to not hog all the available runners
- …
> test: skip reporting CanaryOnly failures for stable version tests

- src/run/headers.test.ts
- src/run/headers.ts
In pages router it is possible to request the page data for a route simply by including the `__nextDataReq` query parameter.
This PR ensures that we include this query param in the cache key to avoid a situation where the JSON data is incorrectly cached in cases with or without the query param.
Unit tests updated
Closes FRB-1413
> fix: add data request query param to the cache key

- tests/e2e/export.test.ts
- tests/e2e/simple-app.test.ts
Preferred format was moved to webp from avif, so this loosens up our assertion to accept either - as long as it's not the same as source image this should ensure there is some processing happening on the image
> test: update assertion to allow image cdn responses be webp

- package-lock.json
- package.json
- src/run/handlers/cache.cts
Specify user agent to help any future debugging related to purge behaviors
https://linear.app/netlify/issue/FRB-1539/pass-custom-user-agent-to-purgecache-calls
> fix: set user agent for purge requests

- edge-runtime/lib/response.ts
- src/run/handlers/server.ts
- tests/e2e/edge-middleware.test.ts
- tests/fixtures/middleware-pages/next-env.d.ts
- tests/fixtures/middleware-pages/next.config.js
- tests/fixtures/middleware-pages/package.json
- tests/fixtures/middleware-pages/tsconfig.json
- tests/integration/edge-handler.test.ts
- tests/integration/page-router.test.ts
- tests/utils/create-e2e-fixture.ts
Adjusts middleware handling to use json data urls and not route paths with `__nextDataReq` query param (that no longer works with recent next@canary after https://github.com/vercel/next.js/pull/74100) for middleware json data rewrites
--- 
Initial previous attempt description below (this felt the quickest "hot fix" but it seemed really wrong to do so):
~This is attempting to address changes made in https://github.com/vercel/next.js/pull/74100 by keeping previous query param "working".~
~This feels like wrong approach to me, but I'm not quite sure how this should be fixed properly. In our middleware handling we are relying on this search param:~ https://github.com/opennextjs/opennextjs-netlify/blob/c3e328c67aee611f83567ebf95c86abcfdd52d93/edge-runtime/lib/response.ts#L182-L186 
~Maybe …
> fix: adjust middleware json data rewrite to work with recent next@canary

- src/build/functions/edge.ts
This reduces the amount of memory being used by the function, base64 will use four thirds of the original size, whereas using uint8array will use the same size as the original size
> fix: use uint8array for htmlrewriter wasm module instead of base64

- edge-runtime/vendor.ts
- src/build/functions/edge.ts
Similar as https://github.com/opennextjs/opennextjs-netlify/pull/2739 but this time for wasm modules used by user in middleware (and not wasm module we built into middleware).
Also allows us to drop direct `https://deno.land/std@0.175.0/encoding/base64.ts` dependency (we still have as indirect one tho :) )
We already have test that would caught regression - https://github.com/opennextjs/opennextjs-netlify/blob/25f6f300f481483ab445cf6fb2b9d181d50d2637/tests/integration/wasm.test.ts#L61-L77
> fix: use uint8array for user's wasm modules used in middleware instead of base64

- src/run/handlers/server.ts
- src/run/headers.ts
We are considering caching 308 trailing slash redirects to reduce function invocations.
This PR will allow us to see the impact of this change.
> feat: add logging to understand impact of trailing slash 308s

- src/run/headers.ts
Update to #2743 to better understand whether we are capturing the right condition to match trailing slash redirects.
> chore: add location header to trailing slash log

- .github/workflows/e2e-report.yml
default github actions image was updated to ubuntu24 which removed globally provided netlify-cli, so attempting to `npx netlify` from root of repo in this workflow won't work, because we only install dependencies inside `e2e-report` dir - so this moves working dir from root to `e2e-report` to be able to use locally installed cli
1. TODO
> ci: run deploy command from e2e-report dir

- .github/workflows/test-e2e.yml
- tests/netlify-deploy.ts
We are currently hitting 120 minutes timeout when running Next.js repo e2e tests ( https://github.com/opennextjs/opennextjs-netlify/actions/runs/12981472164/job/36199955881 as an example) and because of that we don't have successful test run we can use to produce more up-to-date report.
This does increase number of shards we use, and also at least temporarily disable non-latest version runs (to somewhat limit impact of github action concurrency limit we currently have)
https://linear.app/netlify/issue/FRB-1604/fix-vercelnextjs-e2e-report
> ci: increase number of shards when running Next.js repo e2e tests

- src/build/content/static.ts
- src/index.ts
- tests/utils/fixture.ts
- tests/utils/playwright-helpers.ts
We currently use default cache-control for `_next/static` which is `public,max-age=0,must-revalidate` while it should be `public,max-age=31536000,immutable` (per https://nextjs.org/docs/app/api-reference/config/next-config-js/headers#cache-control) as those assets have content hash in filename and therefore should be just permamently cached by browser without the need to revalidate with CDN
Added global automatic fixture that ~passively assert `_next/static` responses cache-control header
https://linear.app/netlify/issue/FRB-1642/set-immutable-cache-control-headers-for-immutable-nextjs-assets
> fix: set immutable cache-control for _next/static

- src/build/functions/edge.ts
- tests/e2e/edge-middleware.test.ts
- tests/fixtures/middleware-i18n-excluded-paths/middleware.ts
- tests/fixtures/middleware-i18n-excluded-paths/next-env.d.ts
- tests/fixtures/middleware-i18n-excluded-paths/next.config.js
- tests/fixtures/middleware-i18n-excluded-paths/package.json
- tests/fixtures/middleware-i18n-excluded-paths/pages/[[...catchall]].tsx
- tests/fixtures/middleware-i18n-excluded-paths/pages/api/[[...catchall]].ts
- tests/fixtures/middleware-i18n-excluded-paths/tsconfig.json
- tests/prepare.mjs
- tests/utils/create-e2e-fixture.ts
Next.js produce very wide matcher for i18n path segment in localized path ( https://github.com/vercel/next.js/blob/5e236c9909a768dc93856fdfad53d4f4adc2db99/packages/next/src/build/analysis/get-page-static-info.ts#L332-L336 ) which is `[^/.]{1,}` that will match on any single path segment. If user attempt to exclude path like `api` as described in one of https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher examples: 
```
export const config = {
matcher: [
/*
* Match all request paths except for the ones starting with:
* - api (API routes)
* - _next/static (static files)
* - _next/image (image optimization files)
* - favicon.ico, sitemap.xml, robots.txt (metadata files)
*/
'/((?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt).*)',
],
}
``` …
> fix: narrow down middleware i18n locale matcher to concrete locales

- src/run/handlers/cache.cts
- src/shared/cache-types.cts
- tests/e2e/page-router.test.ts
- tests/fixtures/wasm-src/src/app/og-node/route.js
- tests/fixtures/wasm-src/src/app/og/route.js
- tests/fixtures/wasm/app/og-node/route.js
- tests/fixtures/wasm/app/og/route.js
Adjustment to `revalidate` tracking after https://github.com/vercel/next.js/pull/76207
No new tests - we already have tests that were failing with latest/canary versions and this change make them pass again
Some unrelated test fixes:
1. For cache-status durable cache value changes
2. For windows failing to build fixtures on next@<15 ( problem described in https://github.com/opennextjs/opennextjs-netlify/pull/2772 as standalone, but might as well get it here in one go )
> fix: dynamic not-prerendered routes revalidate tracking

- tests/e2e/edge-middleware.test.ts
- tests/fixtures/middleware-subrequest-vuln/app/[[...wildcard]]/page.js
- tests/fixtures/middleware-subrequest-vuln/app/layout.js
- tests/fixtures/middleware-subrequest-vuln/middleware.ts
- tests/fixtures/middleware-subrequest-vuln/next.config.js
- tests/fixtures/middleware-subrequest-vuln/package.json
- tests/utils/create-e2e-fixture.ts
This is ensuring Next.js apps hosted on Netlify are not affected by https://github.com/advisories/GHSA-f82v-jwr5-mffw
Our custom edge middleware implementation doesn't make use of `x-middleware-subrequest` header. But just for good measure - let's add test ensuring that suppling this header to request against app using vulnerable Next.js version (15.2.2, so one patch before fix for self hosted)
> test: add test ensuring `GHSA-f82v-jwr5-mffw` doesn't affect Next.js on Netlify

- tests/e2e-skip-retry.json
- tests/test-config.json
Updating vercel/next.js test skiping:
- 2 tests using `x-vercel-cache` response header for assertions
- one flaky test that often times out in CI (which I couldn't reproduce locally) that seems to test Next's browser runtime more than any "server" handling
As part of this I also did create those tracking tickets that seems more warranted to have issues and not just be skipped (one of them seems flaky mostly due to test setup, but it does tests important functionality):
https://github.com/opennextjs/opennextjs-netlify/issues/2784
https://github.com/opennextjs/opennextjs-netlify/issues/2785
fixes https://linear.app/netlify/issue/FRB-1706/ensure-next-runtime-e2e-tests-page-has-no-unknown-failures
> test: skip some vercel/next tests

- src/run/handlers/server.ts
- src/run/headers.ts
Reverts https://github.com/opennextjs/opennextjs-netlify/pull/2743
We decided not to go in this direction
Fixes FRB-1486
> chore: remove trailing slash logging (revert #2743)

- src/run/headers.ts
- tests/e2e/page-router.test.ts
Our handling of setting permanent caching headers for fully static pages (pages router, no getStaticProps or getServerSideProps) is impacting other requests when it shouldn't - this focuses on case of api endpoints using `res.revalidate()` but is not fully solving it - it's meant as stop-gap solution to target pretty specific case.
Added a test to verify that `res.revalidate()` endpoints are not cached
Part of https://linear.app/netlify/issue/FRB-1707/next-runtime-is-sending-cdn-cache-control-headers-unexpectedly
> fix: don't set permanent caching header when res.revalidate() was used

- src/run/storage/request-scoped-in-memory-cache.cts
- tests/fixtures/server-components/app/api/zero-length-response/route.ts
- tests/integration/cache-handler.test.ts
Size calculcation for in-memory store in some cases was returning 0 (in particular known case is cacheable route handler with 0-length body).
This PR does few things:
- ensure there is base blob size added to all known blob types so it should never return 0
- add more checks to ensure fallback case also returns positive number
- make crashes related to in-memory cache failures not fatal - this is meant to be optimization, but it should never cause handler to crash and lead to 500 errors. I did add warning reporting so we can spot those cases and adjust handling to get on happy path
Added known case that is causing errors with currently released version
https://linear.app/netlify/issue/FRB-1721/sizecalculation-return-invalid-expect-positive-integer
> fix: handle case of zero-length cacheable route handler responses

- src/run/handlers/cache.cts
- src/run/handlers/request-context.cts
- src/run/handlers/server.ts
This is to help in debugging potential cases of unexpected rsc or html responses for app pages
> fix: add debug information around potential html/rsc response mismatches

- src/run/headers.test.ts
- src/run/headers.ts
next@15.3.0 no longer sets vary with RSC header in it, instead they rely on `_rsc` query param as cache "busting" ( https://github.com/vercel/next.js/pull/77797 )
because Netlify doesn't automatically create variations for query params, we need to explicitly add it ourselves now
1. TODO
> fix: forcefully add _rsc query param to vary

- tests/utils/fixture.ts
Since `waitUntil` was shipped, our integration test's `invokeFunction` was not awaiting background work which resulted in some flakiness - specifically visible on Windows runners. This restore previous behavior
https://linear.app/netlify/issue/FRB-1714/flaky-test-purge-api-is-not-used-when-unstable-cache-cache-entry-gets
> test: wait for background work to finish in integration tests

- .github/workflows/deno-test.yml
- edge-runtime/lib/middleware.test.ts
- edge-runtime/lib/middleware.ts
- edge-runtime/lib/response.ts
These changes make it possible to set a cookie in middleware and have that value be accessible at render time during the same request. This should also address a couple e2e tests failures we see in the report.
Part of FRB-1387
Fixes FRB-1748
Fixes https://github.com/opennextjs/opennextjs-netlify/issues/2669
Used variants of the following setup:
```
// page.tsx
export default async function Page() {
const myCookies = await cookies();
if (!myCookies.has("nextjs-cookie")) {
throw new Error("Cookie not found");
}
return (
<div>
<h1>Page</h1>
<p>Generated by create next app</p>
<p>Cookie: {myCookies.get("nextjs-cookie")?.value}</p>
</div>
);
}
```
```
// middleware.ts
export async function middleware(request: NextRequest) {
const nextRes = NextResponse.next(); …
```
> fix: cookies set in middleware accessible during the same request

- tests/e2e/dynamic-cms.test.ts
See  https://github.com/opennextjs/opennextjs-netlify/actions/runs/14588003174/job/40916950224
this loosens up comparison to allow either `,` or line break separation + some optional whitespaces in case things change in the future to not be so rigid, but still assert important bits
Adjusting existing test assertions
https://linear.app/netlify/issue/FRB-1757/next-runtime-e2e-assertions-failing
> test: allow cache-status to be either comma or line separated

- .github/workflows/run-tests.yml
- .gitignore
- tools/build-helpers.js
- tools/build.js
- tools/vendor-deno-tools.js
Seems like added test in https://github.com/opennextjs/opennextjs-netlify/pull/2862 introduces flakiness when setup up fixture in integration tests. I don't think the test itself is the cause of it, but rather the fact that Vitest run few parallel workers all trying to bundle edge functions at the same time and to do that Deno does download eszip wasm file to same cache location in multiple processes around the same time sometimes causing corruption (and added test is just unfortunate to be likely to hit this problem). This adds a step in CI to vendor modules and wasm files used by eszip helper we use to handle edge functions in integration tests which seems to avoid the problem in my tests ( https://github.com/opennextjs/opennextjs-netlify/actions/runs/14751501851?pr=2882 - do note that …
> chore: vendor deno modules used in integration test helpers

- src/run/handlers/cache.cts
Resolves failures in next@canary integration tests
Ran the code changes with `test all versions` tag to ensure failing canary integration tests are now resolved
Fixes FRB-1770
> fix: add a fallback for loadManifest import path

- .github/workflows/pre-release.yml
- .github/workflows/release-please.yml
- .github/workflows/run-tests.yml
- .github/workflows/size-check.yml
- .github/workflows/test-e2e.yml
Builds currently use `deno@1.46.3` so these changes match us to that version
https://github.com/netlify/buildbot/blob/766d2c1ac7b7596f18b546cb6bf13962d157b033/build-image/noble/Dockerfile#L412
> chore: match deno version to builds

- tests/integration/static.test.ts
Ref: https://github.com/ampproject/amphtml/issues/40279 / https://github.com/vercel/next.js/pull/78640/files#diff-42717fb2172c81da9ea4c84d272fae170a0f3f09a2b9e999b18fce7426551db9R10-R21
Seems like `<link rel="expect" href="#«R»" blocking="render">` is being added now with `next@canary` which is tripping up some of our integration tests that collect links and ensures linked resources do exist - this just removes those particular `<link>`s from being collected in our test
Adjusted 
Fixes https://linear.app/netlify/issue/FRB-1783/integration-test-for-static-resource-failing-with-1540-canary15
> test: update assertions after some react canary changes

- package-lock.json
- package.json
- src/build/content/server.ts
- src/run/config.ts
- src/run/constants.ts
- src/run/handlers/server.ts
- src/run/handlers/tags-handler.cts
- src/run/handlers/use-cache-handler.ts
- tests/fixtures/use-cache/app/api/revalidate/[...slug]/route.ts
- tests/fixtures/use-cache/app/default/use-cache-component/dynamic/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-component/dynamic/ttl-5seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-component/static/ttl-10seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-component/static/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-data/dynamic/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-data/dynamic/ttl-5seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-data/static/ttl-10seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-data/static/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-page/dynamic/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-page/dynamic/ttl-5seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-page/static/ttl-10seconds/[slug]/page.tsx
- tests/fixtures/use-cache/app/default/use-cache-page/static/ttl-1year/[slug]/page.tsx
- tests/fixtures/use-cache/app/helpers.tsx
- tests/fixtures/use-cache/app/layout.js
- tests/fixtures/use-cache/next-env.d.ts
- tests/fixtures/use-cache/next.config.js
- tests/fixtures/use-cache/package.json
- tests/fixtures/use-cache/tsconfig.json
- tests/integration/use-cache.test.ts
- tests/test-setup.ts
This is work in progress to support upcoming [`'use cache'` directive](https://nextjs.org/docs/app/api-reference/directives/use-cache)
Notes:
The primary need for custom Netlify cache handler implementation (the new one, that is used by `'use cache'` directive) is that default implementation is in-memory only. While it seems like at least `default` handler for `use cache` doesn't need entries to be actually persisted - it still need to support tags (see [`cacheTag`](https://nextjs.org/docs/app/api-reference/functions/cacheTag)) properly and in serverless environment it means that we can't use in-memory only tag manifest like the default implementation does and will need to check with some persisted source of truth.
Review notes:
This PR contains also changes from following refactor PRs …
> feat: support 'use cache'

- .github/workflows/run-tests.yml
When running tests against all versions, skip windows segments testing against v13 and v14
Example run: https://github.com/opennextjs/opennextjs-netlify/actions/runs/14850399526/job/41693090360
> ci: exclude windows runs when testing older versions of next.js

- .github/workflows/test-e2e.yml
This doesn't seem to provide any value for us. It just adds some test run time and instability to our suite, since this ends up attempting to read a `test-timings.json` file from disk (fails every time) and then makes a request to fetch timings data from a private Vercel endpoint, which sometimes fails with a 403 for some reason.
N/A
N/A
It was added here without explanation: https://github.com/netlify/next-runtime-minimal/pull/334/commits/7ea73a2c7c6be6a898bdc6174e09a8198848a1cb
> ci: remove `--timings` flag for Next.js repo e2e tests

- src/build/functions/edge.ts
- tests/netlify-deploy.ts
- tests/utils/create-e2e-fixture.ts
Follow up to https://github.com/opennextjs/opennextjs-netlify/pull/2891 + adjustments to e2e setups after recent urls changes
> fix: handle case of env not being defined for edge functions

- tests/test-config.json
This test suite file was moved in https://github.com/vercel/next.js/pull/77630.
This results in it showing up as failed in new reports: https://682e414a03ba12f55c5f417b--runtime-e2e-report.netlify.app/.
Example run here:
https://github.com/opennextjs/opennextjs-netlify/actions/runs/15163298543#summary-42664185436.
I also clarified the `reason` field.
We could do something gross to expect the Netlify default 404 page or configure a custom 404 page that mimics Vercel's... but I don't think it's worth it.
N/A
N/A
> chore: add e2e report skip entry for renamed `basepath.test.ts`

- .github/CODEOWNERS
We missed this when moving to this org. This is why PRs don't get the reviewer auto-assigned!
> chore: fix team name in codeowners

- .github/workflows/run-tests.yml
Changes the windows runner to use the latest version available
Appears to bring the duration of tests running on the windows images back to a normal range
> ci: use windows-2025 runner

- .github/workflows/test-e2e.yml
See inline comments
N/A
N/A
N/A
> ci(e2e): disable e2e test cleanup

- tests/e2e-skip-retry.json
- tests/test-config.json
See https://github.com/vercel/next.js/commit/3f9f403a048f1f3b1419d92f70245d4e8c77ac27.
Some tests were split out of the test file we were referencing into new test files. This adds handling for the new file name. We must keep the previous config to support running tests against older versions.
See example "unknown failure": https://github.com/opennextjs/opennextjs-netlify/actions/runs/15643078756.
N/A
N/A
N/A
> test: add handling for skipped tests moved out of `e2e/basepath/basepath.test.ts`

- src/run/handlers/cache.cts
- tests/fixtures/page-router-base-path-i18n/pages/fallback-true/[slug].js
There was some changes in `next@canary` but break some of our handling. This address one of them. Remaining failing tests are results of regression in `next@canary` (see https://github.com/vercel/next.js/issues/80838 ) which hopefully be addressed in Next.js.
1. TODO
> fix: handle shared-cache-controls rename

- tests/e2e/page-router.test.ts
Follow up to https://github.com/opennextjs/opennextjs-netlify/pull/2974 that adjust assertions for currently failing tests now that `fallback: true` cache-control was fixed in https://github.com/vercel/next.js/pull/80865
> test: loose some assertions for fallback: true e2e tests to allow nonbreaking next@canary changes

- tests/e2e/edge-middleware.test.ts
`next@canary` now are automatically opting into `validateRSCRequestHeaders` (note currently it seems like this is enabled in canary only - https://github.com/vercel/next.js/pull/80954 so possibly won't be applied to future stable releases and will remain canary-only)
This does result in additional 307 redirects for middleware redirects ... and rewrites (!). 
In this PR I adjusted our currently failing tests for cache poisoning to work with that additional redirect
> test: adjust assertions to work with validateRSCRequestHeaders enabled

- edge-runtime/shim/index.js
- src/build/content/server.ts
- src/build/functions/edge.ts
- tests/fixtures/hello-world-turbopack/app/edge-page/page.js
- tests/fixtures/hello-world-turbopack/middleware.ts
- tests/integration/hello-world-turbopack.test.ts
Follow up to https://github.com/opennextjs/opennextjs-netlify/pull/2987
This will attempt to adjust handling to fix:
Previous PR did adjust setup for nodejs pages, but that is not sufficient for full coverage
Expanded turbopack fixture and tests to test edge runtime pages and middleware
> fix: handle edge runtime pages and middleware for turbopack builds

- tests/integration/cache-handler.test.ts
- tests/integration/simple-app.test.ts
- tests/utils/next-version-helpers.mjs
To account for https://github.com/vercel/next.js/pull/82199
1. TODO
> test: adjust assertions for /_not-found being possibly added to prerender manifest

- tests/e2e/cli-before-regional-blobs-support.test.ts
- tests/e2e/dynamic-cms.test.ts
- tests/e2e/edge-middleware.test.ts
- tests/e2e/on-demand-app.test.ts
- tests/e2e/page-router.test.ts
- tests/e2e/simple-app.test.ts
- tests/e2e/turborepo.test.ts
Our e2e are affected by a recent platform change and require the following values to be renamed:
- `netlify-cdn-cache-control` -> `debug-netlify-cdn-cache-control`
- `netlify-cache-tag` -> `debug-netlify-cache-tag`
See https://github.com/netlify/stargate/pull/2987
> chore: rename netlify-cdn-cache-control and netlify-cache-tag

- e2e-report/.eslintrc.json
- e2e-report/app/badge/route.js
- e2e-report/components/copy-badge.js
- e2e-report/data/test-results.json
- e2e-report/eslint.config.js
- e2e-report/next.config.mjs
- e2e-report/package-lock.json
- e2e-report/package.json
Within the e2e-report:
- Upgrade eslint 8 -> 9
- Upgrade next 14 -> 15
> chore: upgrade next + eslint in report

- tests/fixtures/dist-dir/app/api/headers/route.js
- tests/fixtures/middleware-src/src/app/test/next/page.js
- tests/fixtures/middleware-trailing-slash/app/test/next/page.js
- tests/fixtures/middleware/app/test/next/page.js
- tests/fixtures/nx-integrated/apps/custom-dist-dir/app/api/headers/route.js
- tests/fixtures/revalidate-fetch/app/dynamic-posts/[id]/page.js
- tests/fixtures/revalidate-fetch/app/posts/[id]/page.js
- tests/fixtures/revalidate-fetch/app/same-fetch-multiple-times/[id]/page.js
- tests/fixtures/server-components/app/api/static/[slug]/route.ts
- tests/fixtures/server-components/app/product/[slug]/page.js
- tests/fixtures/server-components/app/static-fetch/[id]/page.js
- tests/fixtures/simple/app/api/headers/route.js
Fixtures adjustment for breaking change coming in next@16 and already done in next@canary ( https://github.com/vercel/next.js/pull/84179 )
> test: adjust fixtures to await cookies(), params(), headers()
