test/index.js
This PR improves the fixtures setup a little.
In the current setup, it is not possible to modify files when the current directory is a fixture directory, since we are not in the temporary directory anymore. This PR copies the files from the fixture to the temporary directory instead.
In a nutshell:
- Before each test, we create a temporary directory and change `cwd` to it. That temporary directory is empty by default.
- A test can use a fixture directory by calling `await useFixture(fixtureName)`. This will copy all the files from `./test/fixtures/{fixtureName}/**` to that temporary directory (used as `cwd`). In essence this create a "fake repository" before running the plugin.
- After each test, we remove the temporary directory and change `cwd` to its original value.
=> Improve fixtures setup

helpers/validateNextUsage.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/59
=> Fix `react` peer dependency

.github/workflows/test.yml
Part of https://github.com/netlify/team-dev/issues/1
This tests Node 15 in CI.
=> chore: support Node 15

README.md
=> Fix toml formatting in README

package-lock.json, package.json
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/25
=> remove next as peer dependency

package-lock.json
This upgrades the lock file to the latest version.
=> chore: upgrade lock file

renovate.json5
This add Renovate to automate dependencies upgrades.
=> chore: add Renovate

src/lib/helpers/isDynamicRoute.js
https://netlify.slack.com/archives/C020GQEKC13/p1620071033000400
=> fix: support isDynamicRoute in sls-next >=1.8.0

README.md
cc https://github.com/netlify/netlify-plugin-nextjs/issues/271
=> chore: update README (build details, caveats)

README.md
=> chore: doc included-files in README

src/lib/templates/imageFunction.js
Adds some sharp settings that optimize filesize. sharp recently added these options which previous required something like imageoptim/pngquant
=> fix: add sharp optimizations

renovate.json5
Follow up on https://github.com/netlify/netlify-plugin-nextjs/pull/280
=> chore(deps): ignore fs-extra versions >=10

helpers/resolveNextModule.js
=> chore: remove log

README.md
make description agree with command updates in fa8bb50f3237db6457d0f8f4a94ff9afeaec45b6
=> Change installation step #2 description

.github/workflows/fossa.yml
This fixes broken fossa install
=> chore: manually install fossa

src/lib/pages/getStaticProps/setup.js, src/tests/__snapshots__/basePath.test.js.snap, src/tests/__snapshots__/defaults.test.js.snap, src/tests/__snapshots__/i18n.test.js.snap, src/tests/fixtures/pages/404.js, src/tests/i18n.test.js
Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/591
snapshot updates are just because i added a custom 404 to the test fixtures (/pages)
=> fix: move locale/404 to publishPath/404 if custom 404

src/helpers/files.js, test/index.js
Fix a bug where missing middleware causes a build error
=> fix: gracefully handle missing middleware

demos/nx-next-monorepo-demo/package-lock.json, demos/nx-next-monorepo-demo/package.json
Removes the plugin as a dependency of the Nx demo, as it will be using the local version instead
1. Visit the Deploy Preview logs
---
=> chore: remove plugin dep

.github/ISSUE_TEMPLATE/bug_report.yml
Adds linebreaks so that the code fences work
=> chore: fix bug report template syntax

.github/workflows/pre-release.yml, .github/workflows/release-please.yml
Turns out I didn't properly understand how this works, so let's switch back to the "normal" way to do this then ask for advice from one of our GH experts
=> chore: remove "environment" from release-please workflow

.github/workflows/release-please.yml
Add a step to install deps for release-please
=> chore: install deps for release-please

cypress/integration/default/default.spec.ts
Fixes a broken test due to changed copy. 
Re-enabled the cypress github app now that frontend has it working. 
See cypress doesnt fail
---
=> chore: fix test

.github/workflows/release-please.yml
Auto submits new versions of the plugin to the Netlify plugin directory
Existing tests
https://github.com/netlify/submit-build-plugin-action#usage
---
=> chore: auto submit plugin to Netlify plugin directory

.gitignore, demos/server-components/lib/fetch-data.js, demos/server-components/lib/get-comments.js, demos/server-components/lib/get-item.js, demos/server-components/lib/get-story-ids.js, demos/server-components/lib/time-ago.js, demos/server-components/lib/use-data.js
Add a dir to the rsc demo that had been accidentally gitignored
1. Visit [the Deploy Preview](https://deploy-preview-1314--next-plugin-rsc-demo.netlify.app/)
---
=> ci: add missing dir to rsc demo

demos/nx-next-monorepo-demo/.npmrc, demos/nx-next-monorepo-demo/netlify.toml, demos/nx-next-monorepo-demo/package-lock.json
I'm running into E2E issues on the nx demo site and discovered the package-lock.json was out of date. It doesn't fix my E2E failure issue in #1358, but might as well clean it up.
This fixes an peer dependencies that we should probably sort out at some point.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nrwl/eslint-plugin-nx@13.4.6
npm ERR! Found: @typescript-eslint/parser@5.10.1
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"~5.10.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.10.1
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"~5.10.0" from the root project
npm …
```
=> chore: updated package lock in nx-monorepo demo and use legacy peer deps

demos/base-path/netlify.toml, demos/canary/netlify.toml, demos/default/netlify.toml, demos/middleware/netlify.toml, demos/next-auth/netlify.toml, demos/next-export/netlify.toml, demos/next-i18next/netlify.toml, demos/nx-next-monorepo-demo/netlify.toml, demos/server-components/netlify.toml, demos/static-root/netlify.toml
Expanded the custom ignore command so that any commits to the repo trigger deploy previews.
---
=> chore: made custom ignore command more liberal

.gitignore, package-lock.json
Cypress snapshots were showing up in my git changes, so adding the folder to the .gitignore.
1. This doesn't changed code, so all existing previews should deploy and tests pass.
---
=> chore: added cypress/screenshots to git ignore

package-lock.json, plugin/package.json
=> fix(deps): upgrade ipx

demos/base-path/package.json, demos/next-auth/package.json, demos/next-export/package.json, demos/static-root/package.json, package-lock.json
=> chore: add next to all demos

.github/workflows/add-to-project.yml
Adds an action that will automatically add new issues from this repo to the Ecosystem Frameworks project board
=> chore: add issues to project board automatically

plugin/src/helpers/files.ts
The syntax for relevant parts of the Next server source has changed, so our patches need to change.
---
=> fix: update patch syntax

.release-please-manifest.json, release-please-config.json
Trying to make release-please happy
=> ci: fix release-please

README.md, package-lock.json
This line doesn't appear to be needed anymore
=> chore: Update readme

README.md, packages/next/README.md, packages/runtime/README.md
Creates READMEs for the individual packages, and remove some deprecated parts from the top-level README
---
=> chore: update READMEs

demos/canary/next.config.js, demos/canary/package-lock.json, demos/canary/package.json, packages/runtime/src/helpers/types.ts, packages/runtime/src/helpers/utils.ts, packages/runtime/src/index.ts, test/helpers/utils.spec.ts
Supports both the use of remotePatterns under both the experimental property and within the images property (in v12.3 of next)
1. Visit the Deploy Preview - https://deploy-preview-1607--next-plugin-canary.netlify.app/
Fixes https://github.com/netlify/next-runtime/issues/1601
---
=> feat: support updated remotePatterns configuration

demos/server-components/components/comment.js, demos/server-components/components/meta.js, demos/server-components/package.json, demos/server-components/pages/csr.js, demos/server-components/pages/item.server.js, demos/server-components/pages/rsc.server.js, demos/server-components/pages/slow.server.js, package-lock.json
The server components demo was broken. This updates it from the demo site
1. Ensure the rsc demo builds
---
=> chore: fix RSC demo

packages/runtime/src/templates/ipx.ts
[Related slack thread](https://netlify.slack.com/archives/C01TKAEBP3Q/p1665073053509739)
---
=> fix: remove localPrefix

.github/pull_request_template.md
This is only a document change to the pull request template.
There is nothing to test as it is only a document change.
Closes #1695
---
=> chore: removed comment that is no longer necessary in the pull request template

packages/runtime/src/helpers/edge.ts
see https://netlify.slack.com/archives/C0183KVDHFH/p1684936589886179 for reference
1. TODO
=> fix: remove edge functions beta label

tests/integration/netlify-forms.test.ts
A missing test matcher slipped through the net
=> test: add missing matcher to netlify forms test

.github/workflows/test-e2e.yml, run-local-test.sh, tests/e2e-utils-v2.patch
=> test: add new version of patch for recent changes in next repository and try it if older one doesn't work

tests/test-config.json
See https://671118e7015b9d3ae67c415d--runtime-e2e-report.netlify.app/
=> chore(e2e): add two new test suites to skipped config

src/run/headers.ts
This doesn't fix any known issue, just noticed we didn't check for method in this case so just for safety, we should
=> fix: don't cache POST when serving embedded static html

.github/workflows/lint.yml, tests/test-config.json
Part of https://linear.app/netlify/issue/FRB-1592/fix-dependabot-workflow-for-opennext-repo
=> ci: remove prettier write from CI workflow

tests/test-config.json
See inline comment for context
=> test: skip after Next.js repo tests
